<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Shawn Phillips | Lailara LLC">
<meta name="dcterms.date" content="2026-05-03">

<title>Product Data Readiness Audit</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-67270d1595a62d14f123c043d4fb2f18.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="report_files/libs/core-js-2.5.3/shim.min.js"></script>

<script src="report_files/libs/react-18.2.0/react.min.js"></script>

<script src="report_files/libs/react-18.2.0/react-dom.min.js"></script>

<script src="report_files/libs/reactwidget-2.0.0/react-tools.js"></script>

<link href="report_files/libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet">

<script src="report_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>

<link href="report_files/libs/reactable-0.4.5/reactable.css" rel="stylesheet">

<script src="report_files/libs/reactable-binding-0.4.5/reactable.js"></script>



<link rel="stylesheet" href="assets/report.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#part-1-the-money" id="toc-part-1-the-money" class="nav-link active" data-scroll-target="#part-1-the-money">Part 1: The Money</a>
  <ul class="collapse">
  <li><a href="#the-59000-you-already-pay" id="toc-the-59000-you-already-pay" class="nav-link" data-scroll-target="#the-59000-you-already-pay">The $59,000 you already pay</a></li>
  <li><a href="#what-a-wrong-barcode-costs-when-nobody-is-counting" id="toc-what-a-wrong-barcode-costs-when-nobody-is-counting" class="nav-link" data-scroll-target="#what-a-wrong-barcode-costs-when-nobody-is-counting">What a wrong barcode costs when nobody is counting</a></li>
  <li><a href="#the-waiting-room" id="toc-the-waiting-room" class="nav-link" data-scroll-target="#the-waiting-room">The waiting room</a></li>
  <li><a href="#the-slots-you-dont-get-back" id="toc-the-slots-you-dont-get-back" class="nav-link" data-scroll-target="#the-slots-you-dont-get-back">The slots you don’t get back</a></li>
  <li><a href="#the-691-a-month-problem-nobody-sees" id="toc-the-691-a-month-problem-nobody-sees" class="nav-link" data-scroll-target="#the-691-a-month-problem-nobody-sees">The $691-a-month problem nobody sees</a></li>
  <li><a href="#the-revenue-youre-not-capturing" id="toc-the-revenue-youre-not-capturing" class="nav-link" data-scroll-target="#the-revenue-youre-not-capturing">The revenue you’re not capturing</a></li>
  <li><a href="#the-sku-you-cant-afford-to-ignore" id="toc-the-sku-you-cant-afford-to-ignore" class="nav-link" data-scroll-target="#the-sku-you-cant-afford-to-ignore">The SKU you can’t afford to ignore</a></li>
  </ul></li>
  <li><a href="#part-2-why-it-happens" id="toc-part-2-why-it-happens" class="nav-link" data-scroll-target="#part-2-why-it-happens">Part 2: Why It Happens</a>
  <ul class="collapse">
  <li><a href="#the-open-door-why-the-product-master-is-a-free-for-all" id="toc-the-open-door-why-the-product-master-is-a-free-for-all" class="nav-link" data-scroll-target="#the-open-door-why-the-product-master-is-a-free-for-all">The open door: why the product master is a free-for-all</a></li>
  <li><a href="#the-products-that-matter-most-get-the-least-attention" id="toc-the-products-that-matter-most-get-the-least-attention" class="nav-link" data-scroll-target="#the-products-that-matter-most-get-the-least-attention">The products that matter most get the least attention</a></li>
  <li><a href="#you-are-allocating-resources-to-the-wrong-retailer" id="toc-you-are-allocating-resources-to-the-wrong-retailer" class="nav-link" data-scroll-target="#you-are-allocating-resources-to-the-wrong-retailer">You are allocating resources to the wrong retailer</a></li>
  <li><a href="#one-product-line-already-has-better-outcomes.-the-reason-isnt-what-youd-guess." id="toc-one-product-line-already-has-better-outcomes.-the-reason-isnt-what-youd-guess." class="nav-link" data-scroll-target="#one-product-line-already-has-better-outcomes.-the-reason-isnt-what-youd-guess.">One product line already has better outcomes. The reason isn’t what you’d guess.</a></li>
  </ul></li>
  <li><a href="#part-3-what-to-do-about-it" id="toc-part-3-what-to-do-about-it" class="nav-link" data-scroll-target="#part-3-what-to-do-about-it">Part 3: What to Do About It</a>
  <ul class="collapse">
  <li><a href="#ninety-minutes-against-35000" id="toc-ninety-minutes-against-35000" class="nav-link" data-scroll-target="#ninety-minutes-against-35000">Ninety minutes against $35,000</a></li>
  <li><a href="#whats-still-broken-right-now" id="toc-whats-still-broken-right-now" class="nav-link" data-scroll-target="#whats-still-broken-right-now">What’s still broken right now</a></li>
  <li><a href="#how-to-read-the-triage-list" id="toc-how-to-read-the-triage-list" class="nav-link" data-scroll-target="#how-to-read-the-triage-list">How to read the triage list</a></li>
  <li><a href="#monday-morning" id="toc-monday-morning" class="nav-link" data-scroll-target="#monday-morning">Monday morning</a></li>
  <li><a href="#the-sequence" id="toc-the-sequence" class="nav-link" data-scroll-target="#the-sequence">The sequence</a></li>
  </ul></li>
  <li><a href="#part-4-the-evidence" id="toc-part-4-the-evidence" class="nav-link" data-scroll-target="#part-4-the-evidence">Part 4: The Evidence</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="report.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Product Data Readiness Audit</h1>
<p class="subtitle lead">Cinderhaven Provisions · May 2026</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Shawn Phillips | Lailara LLC </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 3, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="part-1-the-money" class="level1">
<h1>Part 1: The Money</h1>
<p>By the end of 2027, every barcode in American retail will change. GS1 Sunrise 2027 transitions the industry from linear barcodes to 2D barcodes built on GS1 Digital Link: a QR code whose foundation is a valid GTIN. Not a GTIN that looks right to a human eye. A GTIN that passes algorithmic validation. Nine of Cinderhaven’s 90 SKUs carry GTINs that do not pass. Those nine SKUs cannot participate in the transition until someone corrects a single digit in each record.</p>
<p>Running in parallel, FSMA Rule 204 makes accurate GTINs a federal requirement. FDA food traceability mandates them as the product identifier backbone for tracking food through the supply chain. The barcode that used to be a scanning convenience is becoming the regulatory infrastructure for food safety. This is not a retailer preference. It is law.</p>
<p>These two deadlines land on a company whose product master would fail basic validation at every contracted retailer today. Fifty of 90 SKUs fail Walmart’s required-field check. Those 50 carry $18.2 million in trailing twelve-month revenue, 71% of the catalog. Costco is nearly as exposed. UNFI and Whole Foods less so, but UNFI’s 54% pass rate still puts $14 million at risk.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Retailer</th>
<th style="text-align: right;">SKUs failing</th>
<th style="text-align: right;">Revenue at risk</th>
<th style="text-align: right;">Pass rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Walmart</td>
<td style="text-align: right;">50 of 90</td>
<td style="text-align: right;">$18.2M</td>
<td style="text-align: right;">44%</td>
</tr>
<tr class="even">
<td>Costco</td>
<td style="text-align: right;">48 of 90</td>
<td style="text-align: right;">$18.0M</td>
<td style="text-align: right;">47%</td>
</tr>
<tr class="odd">
<td>UNFI</td>
<td style="text-align: right;">41 of 90</td>
<td style="text-align: right;">$14.0M</td>
<td style="text-align: right;">54%</td>
</tr>
<tr class="even">
<td>Whole Foods</td>
<td style="text-align: right;">27 of 90</td>
<td style="text-align: right;">$9.8M</td>
<td style="text-align: right;">70%</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/charts/06_retailer_readiness_revenue_at_risk.png" class="img-fluid figure-img" alt="Horizontal bar chart of TTM revenue at risk per contracted retailer, with Walmart leading at $18.2M."></p>
<figcaption>Revenue at risk by retailer.</figcaption>
</figure>
</div>
<p>These are not projections of what might happen if data quality degrades. They are measurements of the current product master against the current retailer requirements. The data fails now. The only reason the revenue still flows is that nobody has run the audit yet.</p>
<p>The convergence of retailer readiness gaps, GS1 Sunrise, and FSMA 204 is the wall. Each individually would justify fixing the product master. Together, they create a deadline. A company that reaches 2028 with invalid GTINs, missing case dimensions, and 90% OneWorldSync incompleteness will not have a data quality problem. It will have a market access problem.</p>
<p>The $59,000 in annual chargebacks is what dirty data costs when nobody checks. The $18.2 million in at-risk revenue is what it costs when someone does. The GS1 and FSMA transitions are the moment when everyone checks at once.</p>
<section id="the-59000-you-already-pay" class="level2">
<h2 class="anchored" data-anchor-id="the-59000-you-already-pay">The $59,000 you already pay</h2>
<p>Cinderhaven’s four contracted retailers deducted $88,000 in chargebacks from settlement payments over the past 18 months. Annualized, that’s $59,000 a year in revenue that left the building before it reached the bank account. Most of it was unnecessary.</p>
<p>Not all chargebacks are created equal. Walmart charges you when your barcode fails a check digit validation. Costco charges you when the case dimensions in the product master don’t match what arrives at the warehouse. UNFI charges you when a required data field is blank. Late deliveries and short shipments also generate charges, but those are logistics problems. This report is about the other kind: the charges that come from wrong, missing, or incomplete product data. Those account for 96% of the chargeback bill.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/charts/14_chargeback_by_reason.png" class="img-fluid figure-img" alt="Horizontal bar chart breaking down chargeback dollars by reason, with three data-defect reasons (Invalid GTIN/UPC, Dimension mismatch, Missing product data) accounting for 96% of dollars."></p>
<figcaption>Chargeback dollars by reason.</figcaption>
</figure>
</div>
<p>Five SKUs generate half of that bill. Fifteen generate 80%. Forty of your 90 SKUs have never been charged back at all. This is not a catalog-wide crisis. It is a concentrated problem with specific names and specific causes. Here are the names:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 30%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>SKU</th>
<th>Product</th>
<th style="text-align: right;">18-mo chargebacks</th>
<th>What’s still broken</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CHP-0002</td>
<td>Spicy Arrabbiata</td>
<td style="text-align: right;">$12,427</td>
<td>GTIN check digit, brand owner blank</td>
</tr>
<tr class="even">
<td>CHP-0044</td>
<td>Charred Scallion Relish</td>
<td style="text-align: right;">$11,740</td>
<td>GTIN check digit, case weight implausible</td>
</tr>
<tr class="odd">
<td>CHP-0043</td>
<td>Cranberry Mostarda</td>
<td style="text-align: right;">$9,882</td>
<td>GTIN check digit, case dims blank</td>
</tr>
<tr class="even">
<td>CHP-0069</td>
<td>Infused Oil, Lemon Herb</td>
<td style="text-align: right;">$8,356</td>
<td>GTIN check digit, case dims blank</td>
</tr>
<tr class="odd">
<td>CHP-0086</td>
<td>Toasted Sesame Oil</td>
<td style="text-align: right;">$5,527</td>
<td>GTIN check digit, case weight implausible</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/charts/01_chargeback_pareto.png" class="img-fluid figure-img" alt="Pareto curve showing 5 SKUs account for 50% of chargeback dollars and 15 SKUs account for 80%."></p>
<figcaption>Chargeback Pareto: a small number of SKUs drive most of the cost.</figcaption>
</figure>
</div>
<p>Every one of these has an invalid GTIN-14 check digit. Every one has at least one other defect layered on top. And every one of these defects is present in the product master right now. Not last year. Not at the time of the last audit. Right now. The charges arrived last month because the same wrong digit that generated the charge the month before is still wrong.</p>
</section>
<section id="what-a-wrong-barcode-costs-when-nobody-is-counting" class="level2">
<h2 class="anchored" data-anchor-id="what-a-wrong-barcode-costs-when-nobody-is-counting">What a wrong barcode costs when nobody is counting</h2>
<p>CHP-0002, Spicy Arrabbiata, is the centerpiece of this finding and gets its own section below. But the pattern it represents is worth understanding first through a simpler example.</p>
<p>CHP-0044, Charred Scallion Relish, has one data defect that generates chargebacks: an invalid GTIN-14 check digit. One field. One wrong number. It generated $4,568 in the last six months, about $760 a month, arriving as line items on four different retailer settlement statements. Nobody at Cinderhaven has connected these four monthly line items to each other, because nobody has a process for tracing chargebacks back to specific fields in the product master. The charges look like four separate problems. They are one problem, four times.</p>
<p>Fixing CHP-0044’s check digit takes ten minutes. Open the product master. Recalculate the check digit. Type the correct number. Save. Ten minutes against $9,136 a year. That ratio does not require a business case. It requires someone to know the connection exists.</p>
</section>
<section id="the-waiting-room" class="level2">
<h2 class="anchored" data-anchor-id="the-waiting-room">The waiting room</h2>
<p>There is an invisible queue between the moment a retailer authorizes a product and the moment that product generates its first sale. At Cinderhaven, the length of that queue is determined almost entirely by the quality of the product data.</p>
<p>CHP-0022, San Marzano Marinara, was authorized at its first retailer on June 3, 2024. It carries four data defects: an invalid GTIN-14, an invalid UPC-12, a blank brand owner, and missing case dimensions. The retailer’s item setup system received the authorization, attempted to validate the product record, and stalled. The GTIN didn’t pass. The case dimensions were blank, so the warehouse management system couldn’t assign a slot. The record sat in a validation queue while the shelf space it had been allocated sat empty. The first scan didn’t register until July 13. Forty days after the buyer had already approved the product.</p>
<p>A SKU with clean data clears that same queue in 10 days. The difference is not processing speed. It is not retailer bureaucracy. It is the number of automated validation checks that return errors instead of passing, each one adding a manual review step, a correction request back to the vendor, and a resubmission cycle before the product can flow to the distribution center.</p>
<p>Forty days is not the worst case. It is typical for the worst quarter of the catalog:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Data quality tier</th>
<th style="text-align: right;">Mean days to shelf</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Worst 25%</td>
<td style="text-align: right;">32 days</td>
</tr>
<tr class="even">
<td>Below average</td>
<td style="text-align: right;">29 days</td>
</tr>
<tr class="odd">
<td>Above average</td>
<td style="text-align: right;">13 days</td>
</tr>
<tr class="even">
<td>Best 25%</td>
<td style="text-align: right;">10 days</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/charts/02_time_to_shelf.png" class="img-fluid figure-img" alt="Dot strip plot showing days from authorization to first scan by data quality tier, with the Worst 25% averaging roughly 3x the Best 25%."></p>
<figcaption>Time-to-shelf by data quality tier.</figcaption>
</figure>
</div>
<p>The 22-day spread between worst and best represents revenue that was approved, authorized, and shelf-allocated, waiting in a system queue for someone to fix a data field. Not waiting for a buyer decision. Not waiting for a logistics window. Waiting for a digit to be corrected in a record that nobody at Cinderhaven knew was wrong, because nobody at Cinderhaven tracks authorization-to-first-scan as a metric.</p>
<p>This is the cost that doesn’t have a line item. Chargebacks arrive as deductions on a settlement statement. Stalled revenue doesn’t arrive at all. It is the absence of revenue during a window when revenue should have been flowing. Nobody notices because there is no alert, no report, no dashboard that says “this product was authorized 30 days ago and hasn’t scanned yet.” The authorization is celebrated. The gap is never measured. The revenue loss is real but invisible.</p>
<p>At CHP-0022’s daily revenue rate, 30 extra days costs roughly $1,400. That’s a small SKU. Apply the same math across all 46 SKUs outside the best quality tier, scaled by their revenue and their actual time-to-shelf gaps, and the catalog-wide cost is $234,000 a year. This estimate assumes revenue accrues linearly with shelf time and that delayed launch revenue is not recovered in later periods. Both assumptions are conservative. In specialty food, launch windows are competitive and seasonal. A product that misses its first three weeks during a promotional period doesn’t get those weeks back. A competitor’s product fills the gap. The revenue doesn’t shift to next month. It vanishes.</p>
</section>
<section id="the-slots-you-dont-get-back" class="level2">
<h2 class="anchored" data-anchor-id="the-slots-you-dont-get-back">The slots you don’t get back</h2>
<p>The progression from chargebacks to stalled revenue to shelf loss follows a severity curve. Chargebacks take your money. Stalled launches take your time. Shelf loss takes your position.</p>
<p>CHP-0069, Infused Oil, Lemon Herb, was authorized across 248 Walmart stores. It carries three data defects: an invalid GTIN-14, an invalid UPC-12, and missing case dimensions. Over the first ten months of its Walmart authorization, these defects generated a steady trickle of chargebacks. Two events, $822. Small enough to disappear into the settlement statement. Not small enough for Walmart’s compliance system to ignore.</p>
<p>In March 2025, Walmart deauthorized CHP-0069 at two stores. Store WMT-0408 on March 3. Store WMT-0217 three weeks later. The product was pulled from two locations, and two shelf slots were filled by whatever the category manager had next in the queue. Those slots are gone. Winning them back requires a new category review, which happens once a year at Walmart, and a pitch that explains why the product that was pulled for data defects won’t be pulled again.</p>
<p>Two stores out of 248 sounds minor. It isn’t. It’s the signal that Walmart’s system has flagged this SKU. The defects that triggered the deauthorizations at WMT-0408 and WMT-0217 are identical to the defects still present at the other 246 stores. The GTIN is still invalid. The case dimensions are still blank. Since the two deauthorizations, Walmart has issued 18 more chargeback events against CHP-0069 at the remaining stores, totaling $6,699. The charges are running at $400 to $500 a month with no sign of stopping. The two deauthorized stores were not the punishment. They were the warning shot. The unfixed data is the loaded gun still pointed at the other 246.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/charts/11_deauth_rate_by_quality_tier.png" class="img-fluid figure-img" alt="Bar chart showing bottom-half quality SKUs are deauthorized at roughly 4.5x the rate of top-half SKUs."></p>
<figcaption>Deauthorization rate by data quality tier.</figcaption>
</figure>
</div>
<p>The pattern is not unique to CHP-0069. Bottom-half data quality SKUs get deauthorized at 4.5 times the rate of top-half SKUs. Thirty-one of 45 bottom-half SKUs have lost at least one slot. Fourteen of 45 top-half SKUs have. The data cannot prove that every deauthorization is a direct consequence of data quality. Retailers remove products for many reasons: poor velocity, planogram resets, category rationalization. But the correlation between data quality and deauthorization rate is the strongest signal in this dataset after the chargeback-to-defect linkage. The SKUs with the worst data lose shelf space at 4.5 times the rate. That is not a coincidence that disappears with a larger sample. That is a pattern that gets worse.</p>
<p>The cost of a deauthorization is not the lost revenue at that store. It is the competitive displacement. A specialty food brand does not compete for abstract “shelf space.” It competes for specific slots in specific planograms that are reviewed on 12-to-24-month cycles. Losing a slot to a competitor means that competitor’s product will generate 12 to 24 months of velocity data at that location, data the category manager will use to justify keeping it during the next review. The brand that lost the slot has to overcome a year of incumbent velocity data with nothing but a pitch deck and a promise. The cost is not $400 a month in chargebacks. The cost is two years of competitive disadvantage at every location where the deauthorization spreads.</p>
</section>
<section id="the-691-a-month-problem-nobody-sees" class="level2">
<h2 class="anchored" data-anchor-id="the-691-a-month-problem-nobody-sees">The $691-a-month problem nobody sees</h2>
<p>The nine invalid GTIN check digits in Cinderhaven’s product master have been wrong since the day each SKU was entered. The earliest was entered in June 2024. That was 23 months ago. In those 23 months, nobody corrected a single one of the nine digits. Not because anyone decided the chargebacks were acceptable. Because nobody knew the chargebacks and the digits were connected.</p>
<p>The chain of visibility works like this. A retailer’s automated system validates the GTIN on an inbound shipment or a data feed submission. The check digit fails. The system generates a compliance penalty. The penalty appears as a line item on the next settlement statement, categorized under a heading like “vendor compliance deductions” or “data quality fines.” The settlement statement is 40 pages long. It contains hundreds of line items. The compliance penalties are scattered across pages 12 through 30, interleaved with promotional deductions, logistics credits, and payment adjustments. An individual penalty is $200 to $400. It does not trigger an investigation. It does not cross an approval threshold. It does not generate an alert.</p>
<p>On the other side, the product master sits in whatever system Cinderhaven uses to manage product data. It might be an ERP. It might be a shared Excel file. It might be a combination of both. The GTIN-14 field contains a 14-digit number that was typed once, by whoever set up the SKU, and has not been opened since. Nobody reviews GTIN fields. Nobody runs check digit validations. Nobody has a process for connecting a chargeback on page 14 of a Walmart settlement statement to a digit in row 44 of the product master.</p>
<p>The ops team is not negligent. They are fully occupied. Four retailer portals. Broker coordination. Velocity reports rebuilt by hand every Monday. Trade spend reconciliation. New SKU launches. Promotional planning. Data cleanup is on the list. It is always on the list. It sits between “update the trade spend template” and “fix the label printer” and it never reaches the top because the chargebacks arrive in amounts too small to demand attention and too steady to ever stop on their own.</p>
<p>CHP-0002 has generated 50 chargeback events in 18 months. An average of $691 a month. Fifty times, the system flagged the same wrong digit, generated the same penalty, deducted it from the same settlement, and nobody traced it back. Not because tracing it was hard. Because nobody knew to look.</p>
<p>This is the structural problem beneath all four cost categories. The chargebacks persist because the defects persist. The defects persist because nobody has time to find them. Nobody has time to find them because the cost of each individual defect is too small to surface through normal business processes. The total is $361,000 a year. The individual units are invisible. The system that would make them visible does not exist yet. Part 3 of this report describes what that system looks like.</p>
</section>
<section id="the-revenue-youre-not-capturing" class="level2">
<h2 class="anchored" data-anchor-id="the-revenue-youre-not-capturing">The revenue you’re not capturing</h2>
<p>The cost story is about money leaving. This is about money that never arrives.</p>
<p>Forty of Cinderhaven’s 90 SKUs pass Walmart’s required-field check today. These are the products that could be submitted for a new Walmart line review, a planogram expansion, or a regional test without any data work. They are ready. The data is clean. The barcodes validate. The case dimensions are populated. The OneWorldSync records exist.</p>
<p>Those 40 SKUs generate $7.3 million in trailing twelve-month revenue across all channels. They are, on average, the smaller products in the catalog.</p>
<p>The 50 that fail generate $18.2 million.</p>
<p>This is the inversion that makes the revenue story uncomfortable. The products with the cleanest data are not the biggest sellers. The biggest sellers have the dirtiest data. The catalog’s growth potential is concentrated in exactly the SKUs that cannot pass a retailer readiness check. Every expansion conversation runs into the same wall: the products you most want to expand are the ones whose data isn’t ready to expand with them.</p>
<p>Twenty of those 50 failing SKUs are already shipping to Walmart. They were authorized before the requirements tightened, or before anyone checked. They are generating revenue on borrowed time.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>SKU</th>
<th>Product</th>
<th style="text-align: right;">TTM revenue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CHP-0002</td>
<td>Spicy Arrabbiata</td>
<td style="text-align: right;">$2.71M</td>
</tr>
<tr class="even">
<td>CHP-0071</td>
<td>Balsamic Vinegar, Aged 12yr</td>
<td style="text-align: right;">$2.01M</td>
</tr>
<tr class="odd">
<td>CHP-0043</td>
<td>Cranberry Mostarda</td>
<td style="text-align: right;">$1.51M</td>
</tr>
<tr class="even">
<td>CHP-0042</td>
<td>Everyday Sriracha</td>
<td style="text-align: right;">$1.33M</td>
</tr>
<tr class="odd">
<td>CHP-0009</td>
<td>Classic Bolognese</td>
<td style="text-align: right;">$1.08M</td>
</tr>
<tr class="even">
<td>CHP-0027</td>
<td>Artichoke &amp; Lemon Cream</td>
<td style="text-align: right;">$1.00M</td>
</tr>
<tr class="odd">
<td>CHP-0044</td>
<td>Charred Scallion Relish</td>
<td style="text-align: right;">$974k</td>
</tr>
<tr class="even">
<td>CHP-0038</td>
<td>Cherry Pepper Mostarda</td>
<td style="text-align: right;">$878k</td>
</tr>
<tr class="odd">
<td>CHP-0063</td>
<td>Everything Bagel Seasoning</td>
<td style="text-align: right;">$853k</td>
</tr>
<tr class="even">
<td>CHP-0031</td>
<td>Stone Ground Mustard</td>
<td style="text-align: right;">$736k</td>
</tr>
</tbody>
</table>
<p>$15.1 million in Walmart-channel revenue riding on data that Walmart’s own system would reject. Four of these appear in both this table and the top chargeback offenders list. The data defects are not hypothetical risk. They are already generating deductions on products that are already selling. The risk and the cost are happening simultaneously.</p>
<p>The other 30 failing SKUs are not authorized at Walmart today. They are the expansion queue. If Cinderhaven wants to pitch a Walmart line extension, and at $25 million in revenue scaling toward $55 million, that pitch is coming, those 30 SKUs need their data fixed before the conversation starts. Not during the conversation. Before. A retailer’s category team does not fix vendor data. They evaluate what’s submitted. If the submission fails their automated checks, the conversation ends before a human being ever sees the product.</p>
<p>The counterintuitive finding makes this worse. Failing SKUs have slightly higher average velocity than passing SKUs: 11.3 units per store per week versus 10.6. The products with the worst data are selling faster than the products with the best data. The readiness gate is screening on data completeness, not commercial viability. The products being blocked from expansion are the ones the market wants most.</p>
<p>The gap between “blocked” and “ready” for most of these SKUs is two to three fields. Brand owner. GTIN check digit. Case dimensions. The work is measured in hours, not weeks. The 50 failing SKUs are not 50 product development problems. They are 50 data entry tasks. The difference between $7.3 million in expansion-ready revenue and $25.5 million in expansion-ready revenue is approximately 27 hours of clerical work. That is the most underspent 27 hours in the company.</p>
</section>
<section id="the-sku-you-cant-afford-to-ignore" class="level2">
<h2 class="anchored" data-anchor-id="the-sku-you-cant-afford-to-ignore">The SKU you can’t afford to ignore</h2>
<p>CHP-0002, Spicy Arrabbiata, is the best-selling product in the Cinderhaven catalog. $2.7 million in trailing twelve-month revenue. 774 stores across every channel. Velocity of 10 units per store per week, steady across 53 consecutive weeks. It represents 10.6% of company revenue and over a million dollars in annual gross margin. If Cinderhaven has a flagship, this is it.</p>
<p>It is also the single largest source of chargeback cost in the catalog. Fifty chargeback events over 18 months. $12,427 in penalties deducted from settlement payments across all four contracted retailers. Not clustered in one bad quarter. Not triggered by one bad shipment. Fifty events spread across 18 consecutive months, arriving at a rate of roughly three per month, because the same two data defects trigger the same automated validation failures at the same four retailers, month after month, without interruption.</p>
<p>The defects are not complex. The GTIN-14 check digit is wrong. The brand owner field contains the two-character string “NA” instead of a company name. The OneWorldSync record was never created. The GTIN defect alone accounts for 96% of CHP-0002’s chargeback dollars. Forty-eight of the 50 events trace to a single wrong digit in a single field.</p>
<p>In five of the 18 months, all four contracted retailers flagged CHP-0002 in the same month. Walmart, Costco, UNFI, and Whole Foods, independently running their own validation checks, independently finding the same wrong digit, independently issuing penalties. This is the diagnostic signature of a master data defect: multiple retailers flagging the same SKU for the same reason in the same time window. It is not a dispute about terms. It is not a disagreement about a shipment. It is an automated system doing exactly what it was designed to do, finding a wrong number and charging for it, and it will continue doing it every month until someone changes the number.</p>
<p>CHP-0002 would fail every retailer’s required-field check today. Not one. All four. The product is authorized at 774 stores and its data would not survive the onboarding process at any of them if it were submitted fresh. It was authorized before the checks existed or before they were enforced at their current stringency. It survives on inertia, not on data quality.</p>
<p>The contrast is instructive. CHP-0020, Truffle Mushroom Cream, sits at #3 in the revenue rankings at $1.95 million. Same product line. Comparable scale. Data quality score of 87.5 versus CHP-0002’s 62.5. Two chargeback events in 18 months, totaling $552. Passes all four retailer readiness checks.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">CHP-0002</th>
<th style="text-align: right;">CHP-0020</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TTM revenue</td>
<td style="text-align: right;">$2.71M</td>
<td style="text-align: right;">$1.95M</td>
</tr>
<tr class="even">
<td>Data quality score</td>
<td style="text-align: right;">62.5</td>
<td style="text-align: right;">87.5</td>
</tr>
<tr class="odd">
<td>18-month chargebacks</td>
<td style="text-align: right;">$12,427</td>
<td style="text-align: right;">$552</td>
</tr>
<tr class="even">
<td>Chargeback events</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td>Retailers passing</td>
<td style="text-align: right;">0 of 4</td>
<td style="text-align: right;">4 of 4</td>
</tr>
</tbody>
</table>
<p>Two products at comparable revenue. One generates 22 times more chargeback cost than the other. The 22x gap is not explained by any commercial difference. It is explained entirely by two data fields.</p>
<p>This pattern extends across the top of the catalog:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Rank</th>
<th>Product</th>
<th style="text-align: right;">Revenue</th>
<th style="text-align: right;">DQ score</th>
<th style="text-align: right;">Chargebacks</th>
<th style="text-align: right;">Retailers passing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Spicy Arrabbiata</td>
<td style="text-align: right;">$2.71M</td>
<td style="text-align: right;">62.5</td>
<td style="text-align: right;">$12,427</td>
<td style="text-align: right;">0 of 4</td>
</tr>
<tr class="even">
<td>2</td>
<td>Balsamic Vinegar, Aged 12yr</td>
<td style="text-align: right;">$2.01M</td>
<td style="text-align: right;">87.5</td>
<td style="text-align: right;">$531</td>
<td style="text-align: right;">1 of 4</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Truffle Mushroom Cream</td>
<td style="text-align: right;">$1.95M</td>
<td style="text-align: right;">87.5</td>
<td style="text-align: right;">$552</td>
<td style="text-align: right;">4 of 4</td>
</tr>
<tr class="even">
<td>4</td>
<td>Cranberry Mostarda</td>
<td style="text-align: right;">$1.51M</td>
<td style="text-align: right;">50.0</td>
<td style="text-align: right;">$9,882</td>
<td style="text-align: right;">1 of 4</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Everyday Sriracha</td>
<td style="text-align: right;">$1.33M</td>
<td style="text-align: right;">62.5</td>
<td style="text-align: right;">$229</td>
<td style="text-align: right;">0 of 4</td>
</tr>
<tr class="even">
<td>6</td>
<td>Classic Bolognese</td>
<td style="text-align: right;">$1.08M</td>
<td style="text-align: right;">62.5</td>
<td style="text-align: right;">$1,131</td>
<td style="text-align: right;">1 of 4</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Artichoke &amp; Lemon Cream</td>
<td style="text-align: right;">$1.00M</td>
<td style="text-align: right;">62.5</td>
<td style="text-align: right;">$855</td>
<td style="text-align: right;">0 of 4</td>
</tr>
<tr class="even">
<td>8</td>
<td>Charred Scallion Relish</td>
<td style="text-align: right;">$974k</td>
<td style="text-align: right;">62.5</td>
<td style="text-align: right;">$11,740</td>
<td style="text-align: right;">2 of 4</td>
</tr>
<tr class="odd">
<td>9</td>
<td>Cherry Pepper Mostarda</td>
<td style="text-align: right;">$878k</td>
<td style="text-align: right;">50.0</td>
<td style="text-align: right;">$827</td>
<td style="text-align: right;">0 of 4</td>
</tr>
<tr class="even">
<td>10</td>
<td>Everything Bagel Seasoning</td>
<td style="text-align: right;">$853k</td>
<td style="text-align: right;">62.5</td>
<td style="text-align: right;">$2,018</td>
<td style="text-align: right;">1 of 4</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/charts/08_chargeback_pct_of_gross_margin_top15.png" class="img-fluid figure-img" alt="Horizontal bar chart of chargebacks as a share of gross margin for the top-15 SKUs by revenue, with the worst SKUs disproportionately concentrated near the top of the revenue ranking."></p>
<figcaption>Chargebacks as percentage of gross margin, top 15 SKUs.</figcaption>
</figure>
</div>
<p>Only one of the top 10 passes all four retailers. Six pass zero or one. The $16.1 million in revenue at the top of the catalog, 63% of the company, rides on data that would fail most retailer onboarding processes.</p>
<p>The assumption that the highest-revenue products must have the best data is not just wrong. It is precisely inverted. The products that generate the most revenue received the same one-time data entry as every other product. They just generate larger penalties when that entry is wrong, attract more retailer scrutiny because of their volume, and create more exposure when a readiness audit runs. The risk concentrates at the top because revenue concentrates at the top. The data quality does not.</p>
<p>Fixing CHP-0002 takes 40 minutes. Correct the GTIN check digit. Replace the “NA” in the brand owner field with “Cinderhaven Provisions.” Submit the OneWorldSync registration. When that’s done, $8,300 a year in chargebacks stops and the #1 SKU passes all four retailer readiness checks. The risk that Walmart runs an Item 360 audit and flags the company’s flagship product goes from certain failure to clean pass.</p>
<p>The risk of leaving it unfixed is not the $8,300. The risk is that a retailer runs the check. Walmart doesn’t send a chargeback for a readiness failure. Walmart sends a deauthorization. And when the #1 SKU, 10.6% of company revenue, a million dollars in annual gross margin, loses its largest retailer, the conversation is not with the data team. It is with the board.</p>
</section>
</section>
<section id="part-2-why-it-happens" class="level1">
<h1>Part 2: Why It Happens</h1>
<p>Part 1 showed what data debt costs. This section is about where it comes from. Four causes, each one fixable, none of them surprising once you see them. The frustrating part is how ordinary they are.</p>
<section id="the-open-door-why-the-product-master-is-a-free-for-all" class="level2">
<h2 class="anchored" data-anchor-id="the-open-door-why-the-product-master-is-a-free-for-all">The open door: why the product master is a free-for-all</h2>
<p>Cinderhaven’s product master was built the way most $25 million companies build a product master: by whoever had 20 minutes. Thirteen SKUs were uploaded by a broker. Nineteen were entered by the production admin. Seventeen by inventory admin. Twelve came through an import script. Ten by the quality manager. Ten by an ops coordinator. Nine have no recorded entry source at all. Seven different paths into the same system, and not one of them requires the data to be validated before it goes live.</p>
<p>There is no intake checklist. No required field set enforced at entry. No validation step between “someone typed this” and “retailers are ordering against it.” A broker can upload a SKU with a wrong check digit, a blank brand owner, and missing case dimensions, and the record goes live the moment it’s saved. The first validation that record will ever receive is a retailer’s automated compliance check, six months later, when it fails and generates a $300 penalty that nobody traces back to the upload.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Entry source</th>
<th style="text-align: right;">SKUs</th>
<th style="text-align: right;">Chargebacks per SKU</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>quality_mgr</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">$1,444</td>
</tr>
<tr class="even">
<td>broker_upload</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">$1,435</td>
</tr>
<tr class="odd">
<td>import_script</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">$1,413</td>
</tr>
<tr class="even">
<td>inventory_admin</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">$1,343</td>
</tr>
<tr class="odd">
<td>production_admin</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">$513</td>
</tr>
<tr class="even">
<td>ops_coordinator</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">$269</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/charts/17_process_debt_by_updated_by.png" class="img-fluid figure-img" alt="Bar chart of chargebacks-per-SKU by data entry source, showing four sources clustered around $1,400 and two materially better sources (production_admin, ops_coordinator)."></p>
<figcaption>Process debt by data-entry source.</figcaption>
</figure>
</div>
<p>The conventional reading is that broker uploads are the problem. The table says otherwise. Four different entry paths, operated by four different roles with four different levels of product knowledge, all produce essentially the same expensive result. The problem is not who is entering the data. The problem is that nobody is checking it.</p>
<p>The two sources that produce materially better results share one characteristic the others do not. Production admin and ops coordinator enter data as a primary responsibility, not as an interruption between other tasks. The distinction is not skill or diligence. It is attention. The people who produce clean data are the people whose job makes data entry the main task, not the side task.</p>
<p>This is not fixable by training. Training addresses skill gaps. This is an attention gap. The fix is structural: a gate between data entry and the live product master. The broker intake checklist in the appendix defines eight fields that must be populated and validated before a SKU record can go live. It takes five minutes to fill out. But the checklist is not just for brokers. Every path into the product master needs the same front door because every path without one produces the same result.</p>
<p>The nine SKUs with no recorded entry source at all are a separate finding. They represent a gap not just in data quality but in data governance. Nobody knows who entered these records. Nobody knows when. Nobody knows what process, if any, was followed. These nine SKUs are the clearest evidence that the product master is an unmanaged asset. It is the most important data system in the company, every retailer relationship, every chargeback, every velocity report, every shelf placement depends on it, and it has no owner, no process, and no audit trail.</p>
</section>
<section id="the-products-that-matter-most-get-the-least-attention" class="level2">
<h2 class="anchored" data-anchor-id="the-products-that-matter-most-get-the-least-attention">The products that matter most get the least attention</h2>
<p>The centerpiece section showed CHP-0002 in detail: the #1 revenue SKU with the #1 chargeback total. That’s not an anomaly. It’s the pattern.</p>
<p>The top 15 SKUs by revenue have a mean data quality score of 66.7. The catalog averages 70.0. Six of the top 10 revenue SKUs pass zero or one of four retailer readiness checks. Only one, CHP-0020 Truffle Mushroom Cream, passes all four.</p>
<p>The instinct is to assume this will sort itself out. The big sellers get attention. Attention leads to cleanup. The assumption is wrong because it confuses commercial attention with data attention. Everyone at Cinderhaven knows that Spicy Arrabbiata sells $2.7 million a year. Nobody at Cinderhaven knows that Spicy Arrabbiata’s GTIN-14 check digit is wrong. Those are two different kinds of knowing, and only the first one happens naturally.</p>
<p>Data entry is clerical work. It happens at launch, when somebody has 20 minutes between other tasks, and it never happens again. Nobody revisits the product master after a SKU is selling. The record freezes at whatever state it was in on the day someone typed it. A $2.7 million SKU and a $15,000 SKU both get one pass through data entry. The $2.7 million SKU just generates larger chargebacks when the entry is wrong.</p>
<p>The fix does not require better data entry. It requires a list. Put the revenue number next to every SKU on the ops team’s screen. Sort by revenue. Start at the top. The people doing the work have never been shown which products their work protects. Give them that information and the triage takes care of itself.</p>
</section>
<section id="you-are-allocating-resources-to-the-wrong-retailer" class="level2">
<h2 class="anchored" data-anchor-id="you-are-allocating-resources-to-the-wrong-retailer">You are allocating resources to the wrong retailer</h2>
<p>Walmart generates $13.1 million in gross revenue. That’s 51% of the catalog. It is the largest channel by every gross metric. It is not the most profitable.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Retailer</th>
<th style="text-align: right;">Gross</th>
<th style="text-align: right;">Trade spend</th>
<th style="text-align: right;">Chargebacks</th>
<th style="text-align: right;">Net margin</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Whole Foods</td>
<td style="text-align: right;">$2.78M</td>
<td style="text-align: right;">12.5%</td>
<td style="text-align: right;">0.36%</td>
<td style="text-align: right;"><strong>87.0%</strong></td>
</tr>
<tr class="even">
<td>UNFI</td>
<td style="text-align: right;">$4.27M</td>
<td style="text-align: right;">15.1%</td>
<td style="text-align: right;">0.61%</td>
<td style="text-align: right;">84.3%</td>
</tr>
<tr class="odd">
<td>Costco</td>
<td style="text-align: right;">$2.25M</td>
<td style="text-align: right;">16.4%</td>
<td style="text-align: right;">0.40%</td>
<td style="text-align: right;">82.4%</td>
</tr>
<tr class="even">
<td>Walmart</td>
<td style="text-align: right;">$13.10M</td>
<td style="text-align: right;">21.3%</td>
<td style="text-align: right;">0.33%</td>
<td style="text-align: right;">78.4%</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/charts/03_retailer_net_margin.png" class="img-fluid figure-img" alt="Four-panel waterfall chart per retailer, showing Walmart winning gross dollars and Whole Foods winning margin density."></p>
<figcaption>True net margin by retailer.</figcaption>
</figure>
</div>
<p>Whole Foods contributes 87 cents of margin on every dollar of revenue. Walmart contributes 78 cents. The nine-cent gap is almost entirely trade spend.</p>
<p>This table reorders the CEO’s priorities. Not away from Walmart. Walmart generates $10.27 million in net contribution. You don’t walk away from that. But you stop assuming that Walmart volume equals Walmart profitability when deciding where to invest ops resources, which retailer gets the first call when there’s a data issue, and which expansion opportunity gets prioritized.</p>
<p>The chargeback column reveals something else. The rates are small at every retailer, between 0.33% and 0.61% of revenue. But chargebacks are the only margin lever entirely within Cinderhaven’s control. Trade spend is negotiated once a year. Chargebacks are generated by data defects that Cinderhaven can fix any Tuesday afternoon. Every dollar recovered drops straight to net contribution with no negotiation, no pitch deck, no relationship risk.</p>
<p>UNFI is the overlooked story. It generates $26,000 in chargebacks, 30% of the total, despite being the #2 retailer by revenue. Its chargeback rate (0.61% of revenue) is the highest of the four. UNFI’s compliance requirements are less visible than Walmart’s. The data says they enforce them just as consistently. A cleanup that focuses on Walmart because Walmart is the biggest name leaves $26,000 of UNFI chargebacks untouched and a 0.61% bleed rate unaddressed at the retailer with the second-best margin density.</p>
</section>
<section id="one-product-line-already-has-better-outcomes.-the-reason-isnt-what-youd-guess." class="level2">
<h2 class="anchored" data-anchor-id="one-product-line-already-has-better-outcomes.-the-reason-isnt-what-youd-guess.">One product line already has better outcomes. The reason isn’t what you’d guess.</h2>
<p>Data debt is not evenly distributed.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Product line</th>
<th style="text-align: right;">Revenue</th>
<th style="text-align: right;">Issues per $1M</th>
<th style="text-align: right;">Chargebacks per $1M</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pantry Staples</td>
<td style="text-align: right;">$6.49M</td>
<td style="text-align: right;">11.3</td>
<td style="text-align: right;">$2,506</td>
</tr>
<tr class="even">
<td>Specialty Condiments</td>
<td style="text-align: right;">$8.71M</td>
<td style="text-align: right;">8.5</td>
<td style="text-align: right;">$4,662</td>
</tr>
<tr class="odd">
<td>Artisan Sauces</td>
<td style="text-align: right;">$10.35M</td>
<td style="text-align: right;">6.7</td>
<td style="text-align: right;">$3,013</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/charts/07_data_debt_by_product_line.png" class="img-fluid figure-img" alt="Bar chart of data issues per million dollars of revenue by product line; Pantry Staples carries 70% more issues per dollar than Artisan Sauces."></p>
<figcaption>Data debt by product line.</figcaption>
</figure>
</div>
<p>Pantry Staples carries 70% more data issues per dollar of revenue than Artisan Sauces. The two worst lines are close enough to treat as one cleanup tier. But Artisan Sauces is meaningfully better across every metric.</p>
<p>The obvious hypothesis is that Artisan Sauces routes through a better data entry process. It doesn’t. The cross-tab between product line and entry source shows Artisan Sauces actually over-indexes on quality_mgr, one of the most expensive entry sources at $1,444 in chargebacks per SKU. Specialty Condiments, which has worse outcomes, is the line that disproportionately flows through production_admin, the cleanest source.</p>
<p>The process theory doesn’t hold. Something else is producing Artisan Sauces’ better outcomes despite using expensive entry paths.</p>
<p>Two explanations survive the data. First, Artisan Sauces is the highest-revenue product line. Its SKUs are more likely to have attracted retailer scrutiny, category review attention, and incidental cleanup during quarterly business reviews. Revenue creates visibility. Visibility creates corrections. Second, Artisan Sauces has been in the catalog longest as a line. More time means more cycles through retailer item setup, more rounds of chargeback-driven fixes, more opportunities for someone to notice a defect and correct it. The data is not cleaner by design. It is cleaner by attrition.</p>
<p>Both explanations point to the same conclusion: data quality at Cinderhaven is not managed. It is accidental. The SKUs that get cleaner are the ones that somebody happens to look at for some other reason. A revenue-weighted triage process would make this deliberate instead of incidental. The Artisan Sauces outcome would become the standard, not the exception. And it would happen in weeks, not years.</p>
</section>
</section>
<section id="part-3-what-to-do-about-it" class="level1">
<h1>Part 3: What to Do About It</h1>
<section id="ninety-minutes-against-35000" class="level2">
<h2 class="anchored" data-anchor-id="ninety-minutes-against-35000">Ninety minutes against $35,000</h2>
<p>Nine SKUs have invalid GTIN-14 check digits. A check digit is a mathematical typo: the last digit of a barcode, calculated from the preceding digits using a standard algorithm. It exists so scanning systems can detect keying errors. When the digit is wrong, the barcode fails validation, the retailer issues a penalty, and the penalty arrives on the settlement statement looking like a cost of doing business. It is not. It is a cost of a wrong digit.</p>
<p>Each of the nine takes about ten minutes to fix. The algorithm is deterministic. The input is already in the record. The fix is arithmetic, not judgment.</p>
<p>Those nine SKUs generated $52,661 in chargebacks over 18 months. Annualized, that’s $35,000 a year. 205 chargeback events across all four contracted retailers. Every event was triggered by the same mechanism: a system ran a calculation, compared the result to the digit on file, found they didn’t match, and issued a charge. The digit on file has been wrong since the day each SKU was entered. It is still wrong now.</p>
<p>Ninety minutes of data entry. $35,000 a year. $389 per minute. The return on this fix is not a number that belongs in a business case. It belongs in a case study about organizational blind spots. The fix has been available for as long as the defect has existed. The cost has been accumulating every month. The connection between the two has never been visible because no system, no report, and no process at Cinderhaven links chargebacks to specific fields in the product master. This report is that link. The connection is now visible. What happens next is a decision, not a discovery.</p>
<p>The second fix is case dimensions. Twenty-one SKUs have blank case weight, length, width, or height fields. When a retailer’s warehouse receives a case and attempts to reconcile it against the product master, the master says nothing. Any measurement is a mismatch against a blank field. Someone pulls a case from inventory, measures it with a tape measure and a scale, and enters five numbers. About 30 minutes per SKU. Twenty-one SKUs, roughly 10 to 11 hours total. That eliminates 18% of chargeback dollars: $15,938 over 18 months, approximately $10,600 a year.</p>
<p>The third fix is missing product data. Eighteen SKUs have blank or placeholder values in required fields: brand owner, country of origin, or other retailer-mandated attributes. Seventeen of the eighteen brand owner cases contain the literal string “NA,” two characters typed by whoever set up the SKU instead of the company name. Replacing “NA” with “Cinderhaven Provisions” takes less time than reading this sentence. The other fields require slightly more work: a phone call to a supplier for imported ingredients, a lookup in an internal system for regulatory codes. Call it 15 hours total across 18 SKUs.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Fix action</th>
<th style="text-align: right;">SKUs</th>
<th style="text-align: right;">Time</th>
<th style="text-align: right;">Annual savings</th>
<th style="text-align: right;">Per minute</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fix GTIN check digits</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">90 min</td>
<td style="text-align: right;">$35,000</td>
<td style="text-align: right;">$389/min</td>
</tr>
<tr class="even">
<td>Reconcile case dimensions</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">10.5 hr</td>
<td style="text-align: right;">$10,600</td>
<td style="text-align: right;">$17/min</td>
</tr>
<tr class="odd">
<td>Complete missing fields</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">15 hr</td>
<td style="text-align: right;">$10,400</td>
<td style="text-align: right;">$12/min</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"><strong>~27 hr</strong></td>
<td style="text-align: right;"><strong>$56,000</strong></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/charts/04_fix_roi.png" class="img-fluid figure-img" alt="Horizontal bar chart of chargeback savings per hour of remediation effort, with GTIN check-digit fixes far outpacing every other action."></p>
<figcaption>Fix ROI: chargeback savings per hour of effort, by fix action.</figcaption>
</figure>
</div>
<p>Twenty-seven hours of data entry eliminates $56,000 a year in chargebacks. That is the entire data-defect chargeback bill. Every dollar traces to a field that is currently wrong or currently empty in the product master. The remaining $3,900 a year comes from late deliveries and short shipments, logistics issues outside the scope of a data audit.</p>
<p>The asymmetry between cost and fix is the central finding of this report. Not the $361,000 total. Not the Pareto concentration. Not the retailer readiness gaps. The asymmetry. The fact that a $25 million company is losing $56,000 a year in direct penalties because nobody has spent 27 hours on data entry. The fact that 60% of that cost sits in nine fields that take 90 minutes to correct. The fact that those nine fields have been wrong for an average of 22 months while the charges accumulated in amounts too small to trigger investigation and too steady to ever stop.</p>
</section>
<section id="whats-still-broken-right-now" class="level2">
<h2 class="anchored" data-anchor-id="whats-still-broken-right-now">What’s still broken right now</h2>
<p>This is not history. Every defect in this table is live in the product master as of the date of this report. Every chargeback was incurred in the last six months. The field that caused it has not been corrected.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 17%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>SKU</th>
<th>Product</th>
<th style="text-align: right;">Last 6 months</th>
<th>What’s broken</th>
<th style="text-align: right;">Fix time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CHP-0044</td>
<td>Charred Scallion Relish</td>
<td style="text-align: right;">$4,568</td>
<td>GTIN check digit</td>
<td style="text-align: right;">10 min</td>
</tr>
<tr class="even">
<td>CHP-0002</td>
<td>Spicy Arrabbiata</td>
<td style="text-align: right;">$4,458</td>
<td>GTIN check digit + brand owner</td>
<td style="text-align: right;">40 min</td>
</tr>
<tr class="odd">
<td>CHP-0043</td>
<td>Cranberry Mostarda</td>
<td style="text-align: right;">$3,923</td>
<td>GTIN check digit + case dims</td>
<td style="text-align: right;">40 min</td>
</tr>
<tr class="even">
<td>CHP-0069</td>
<td>Infused Oil, Lemon Herb</td>
<td style="text-align: right;">$2,906</td>
<td>GTIN check digit + case dims</td>
<td style="text-align: right;">40 min</td>
</tr>
<tr class="odd">
<td>CHP-0013</td>
<td>Sun-Dried Tomato Pesto</td>
<td style="text-align: right;">$2,183</td>
<td>GTIN check digit</td>
<td style="text-align: right;">10 min</td>
</tr>
<tr class="even">
<td>CHP-0024</td>
<td>Charred Tomato &amp; Basil</td>
<td style="text-align: right;">$2,137</td>
<td>GTIN check digit</td>
<td style="text-align: right;">10 min</td>
</tr>
<tr class="odd">
<td>CHP-0052</td>
<td>Smoked Chipotle Ketchup</td>
<td style="text-align: right;">$1,736</td>
<td>GTIN check digit</td>
<td style="text-align: right;">10 min</td>
</tr>
<tr class="even">
<td>CHP-0028</td>
<td>Tuscan White Bean Ragu</td>
<td style="text-align: right;">$1,003</td>
<td>Case dims + case weight</td>
<td style="text-align: right;">30 min</td>
</tr>
<tr class="odd">
<td>CHP-0063</td>
<td>Everything Bagel Seasoning</td>
<td style="text-align: right;">$675</td>
<td>Case dims + case weight</td>
<td style="text-align: right;">30 min</td>
</tr>
<tr class="even">
<td>CHP-0027</td>
<td>Artichoke &amp; Lemon Cream</td>
<td style="text-align: right;">$637</td>
<td>Case dims + case weight</td>
<td style="text-align: right;">30 min</td>
</tr>
</tbody>
</table>
<p>Thirty-one SKUs in total carry unfixed defects that are actively generating charges. The ten above account for $24,226 in the last six months. Of the $34,528 in total chargebacks during that period, 92% trace to defects that remain in the product master today.</p>
<p>CHP-0044 is the distillation of the entire problem. One SKU. One defect. One wrong digit. Ten minutes to fix. $4,568 in penalties over six months that would not have occurred if someone had spent ten minutes on this product at any point in the last two years. The reason nobody spent those ten minutes is not negligence or budget or competing priorities. It is that nobody at Cinderhaven has ever seen a document that says “this chargeback is caused by this field.” The settlement statement says “compliance deduction, $287.” The product master says “GTIN-14: 10614141000415.” Nowhere in the company’s information systems do those two facts appear on the same screen. This table is that screen.</p>
</section>
<section id="how-to-read-the-triage-list" class="level2">
<h2 class="anchored" data-anchor-id="how-to-read-the-triage-list">How to read the triage list</h2>
<p>The interactive table below ranks all 90 SKUs by fix priority. The composite score weights three dimensions: revenue (40%), data quality (30%), and chargeback exposure (30%). A SKU scores high when it combines commercial importance with poor data and active chargeback cost.</p>
<p>The effort column sits alongside the composite, not inside it. This is deliberate. Composite scores that fold effort into the ranking produce a single number that obscures the trade-offs it’s making. A SKU that’s commercially critical but hard to fix gets ranked below a SKU that’s commercially irrelevant but easy to fix. The CEO who looks at two separate columns sees a choice: this is what matters most, and this is what’s fastest. Both are useful. Neither is a substitute for the other.</p>
<p>In practice, the two columns produce different action plans. The composite says: start with CHP-0002 because it’s the #1 revenue SKU with the #1 chargeback total. The effort column says: start with CHP-0044 because it’s a 10-minute fix that stops $4,568 in recent chargebacks. A CEO uses the composite to set the quarterly agenda. An ops manager uses the effort column to fill Tuesday afternoon. Both are correct. The table gives both without forcing a false synthesis.</p>
<div class="cell">
<div class="cell-output-display">
<div class="reactable html-widget html-fill-item" id="htmlwidget-5de52b9409be9c7ade03" style="width:auto;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-5de52b9409be9c7ade03">{"x":{"tag":{"name":"Reactable","attribs":{"data":{"SKU":["CHP-0043","CHP-0002","CHP-0069","CHP-0044","CHP-0038","CHP-0001","CHP-0063","CHP-0009","CHP-0027","CHP-0031","CHP-0011","CHP-0012","CHP-0028","CHP-0042","CHP-0086","CHP-0052","CHP-0057","CHP-0025","CHP-0007","CHP-0024","CHP-0010","CHP-0079","CHP-0049","CHP-0090","CHP-0061","CHP-0020","CHP-0071","CHP-0060","CHP-0073","CHP-0040","CHP-0021","CHP-0013","CHP-0089","CHP-0022","CHP-0056","CHP-0033","CHP-0059","CHP-0039","CHP-0084","CHP-0045","CHP-0062","CHP-0081","CHP-0068","CHP-0046","CHP-0083","CHP-0076","CHP-0053","CHP-0075","CHP-0080","CHP-0019","CHP-0015","CHP-0023","CHP-0078","CHP-0064","CHP-0058","CHP-0041","CHP-0085","CHP-0077","CHP-0036","CHP-0035","CHP-0082","CHP-0017","CHP-0037","CHP-0050","CHP-0066","CHP-0070","CHP-0005","CHP-0004","CHP-0008","CHP-0087","CHP-0030","CHP-0054","CHP-0018","CHP-0003","CHP-0088","CHP-0034","CHP-0029","CHP-0072","CHP-0065","CHP-0051","CHP-0006","CHP-0032","CHP-0014","CHP-0055","CHP-0026","CHP-0074","CHP-0067","CHP-0047","CHP-0048","CHP-0016"],"Product":["Cranberry Mostarda","Spicy Arrabbiata","Infused Oil - Lemon Herb","Charred Scallion Relish","Cherry Pepper Mostarda","Roasted Tomato Basil Marinara","Everything Bagel Seasoning","Classic Bolognese","Artichoke & Lemon Cream","Stone Ground Mustard","Calabrian Chili Marinara","Roasted Garlic Pomodoro","Tuscan White Bean Ragu","Everyday Sriracha","Toasted Sesame Oil - Cold Pressed","Smoked Chipotle Ketchup","Harissa Paste","Spicy Vodka Rigatoni Sauce","Lemon Caper Piccata","Charred Tomato & Basil","Heirloom Tomato & Olive","Truffle Salt","Roasted Beet Horseradish","Coffee & Cocoa Rub","Artisan Breadcrumbs - Italian Herb","Truffle Mushroom Cream","Balsamic Vinegar - Aged 12yr","Calabrian Chili Honey","White Wine Vinegar","Habanero Mango Hot Sauce","Balsamic Onion Marinara","Sun-Dried Tomato Pesto","Mediterranean Spice Blend","San Marzano Marinara","Tamarind Date Chutney","Smoked Peach Chutney","Everything Bagel Aioli","Herb Garden Hot Sauce","Infused Oil - Basil","Maple Dijon Mustard","Artisan Breadcrumbs - Garlic Parmesan","Champagne Vinegar","Olive Oil - Everyday Blend","Gochujang Aioli","Infused Oil - Chili Garlic","Za'atar Seasoning Blend","Fermented Hot Sauce","Artisan Breadcrumbs - Panko Style","Black Garlic Powder","Fra Diavolo","Romesco Sauce","Roasted Poblano Verde","Smoked Sea Salt Flake","Smoked Paprika & Garlic Rub","Preserved Lemon Relish","Smoky Ghost Pepper Sauce","Olive Oil - Single Estate Greek","Herbes de Provence","Roasted Garlic Aioli","Fig & Balsamic Spread","Sherry Vinegar - Aged","Arugula & Pistachio Pesto","Spicy Honey Mustard","Black Garlic Aioli","Chile Lime Seasoning","Infused Oil - Roasted Garlic","Fire Roasted Red Pepper","Garlic & Herb Alfredo","Vodka Cream Sauce","Artisan Croutons - Sourdough","Smoked Tomato Bisque Sauce","Miso Ginger Glaze","Putanesca","Wild Mushroom Ragu","Artisan Croutons - Herb & Butter","Pickled Jalapeno Relish","Red Pepper Romesco","Red Wine Vinegar - Reserve","Tuscan Herb Blend","Carolina Gold BBQ","Smoky Chipotle Marinara","Bourbon Onion Jam","Basil Walnut Pesto","Thai Chili Lime Sauce","Garden Herb Marinara","Apple Cider Vinegar - Raw","Olive Oil - Extra Virgin Reserve","Umami Chili Crisp","Green Tomato Chutney","Green Goddess Pesto"],"TTM revenue":[1505499.6,2705914.39,405791.67,974136.5,877588.88,363215.52,852515.07,1079084.86,1001181.72,735735.87,649310.38,173361.92,256859.83,1326226.91,224867.34,207471.67,738712.22,223334.82,28849.92,387580.12,170823.95,338998.32,150907.56,168764.34,612018.98,1954879.19,2011247.01,252186.54,518124.38,211580.5,24962.9,131415.69,24722,17487.59,136476.4,214225.26,240560.7,14984,210662.7,82735.3,60725.78,207829.13,19854.39,592681.08,139870.56,17593.89,156529.56,131443.22,11573.21,96598.08,53409.67,496256.55,146266.26,22536.28,23498.5,128338.38,107273.62,101299.38,15014.27,79890.98,1454.52,55692.09,7631.5,5728.8,47882.5,40899.55,3498.3,37059.58,132098.74,24917.75,103386.76,1493.32,89674.86,38430.12,9208.44,7553.65,25895.25,3602.48,23610.56,3214.56,2721.02,2674.58,21690.86,2570.4,19072.2,1776.25,236.55,12692.35,4170.88,2468.2],"Quality score":[50,62.5,50,62.5,50,50,62.5,62.5,62.5,62.5,62.5,50,62.5,62.5,62.5,62.5,75,62.5,37.5,75,50,62.5,62.5,62.5,75,87.5,87.5,75,75,75,62.5,75,50,50,75,75,75,62.5,75,62.5,62.5,75,62.5,75,75,62.5,75,75,50,62.5,62.5,87.5,75,75,62.5,75,75,75,62.5,75,50,75,62.5,62.5,75,75,62.5,100,87.5,75,87.5,62.5,87.5,87.5,75,75,87.5,75,87.5,75,75,75,87.5,75,87.5,75,75,87.5,87.5,87.5],"Chargebacks 18mo":[9882.29,12426.84,7520.91,11740.14,826.71,1890.41,2018.33,1131.22,854.92,1035.59,1039.97,1082.98,1342.85,228.83,1813.27,4760.93,6773.02,740.08,1651.25,4031.78,119.31,201.11,632.42,549.06,635.6,552.2,531.37,561.95,225.61,805.24,1212.36,2183.34,454.44,689.13,1172.91,375.7,200.18,1435.56,219.03,95.74,107.92,187.74,490.91,0,221.16,483.57,90.35,215.93,84.55,0,0,0,0,297.41,0,0,0,0,0,0,0,0,0,0,0,0,0,221.19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"Composite priority":[95.1,90.6,88.5,87.1,86.5,85.6,83.9,83,81.2,79.3,79.2,77.6,76.9,76.8,76.6,75.6,74.1,71.8,69.9,69.9,67.8,67.7,66.3,66.2,65.8,61.5,61.3,61.1,60.9,60.6,59.7,59.3,58.9,58.4,58,57,55.3,55,54.1,53.6,53,52.3,50.9,50.5,50.4,49.7,48.8,48.4,48.3,46.9,44.3,41.4,40.7,39.8,39.4,38.1,37.6,36.7,36.3,34.9,34.8,34.1,34.1,33.2,33.2,32.7,31.8,31.7,31.2,30.1,29,28.7,27.7,24.1,23.8,22.9,22.8,21.6,21,20.7,20.3,19.8,19.7,19.4,18.8,18.5,17.2,16.6,13.9,10.8],"Est. fix hours":[1.17,0.83,1.17,0.92,1.17,1.5,1,1,1,1,1,1.17,1,0.92,0.92,0.92,0.75,1,1.33,0.67,1.5,1,0.92,1,0.75,0.5,0.5,0.75,0.75,0.42,1.17,0.67,1.17,1.17,0.75,0.75,0.75,0.83,0.75,0.92,1,0.75,0.67,0.75,0.75,1,0.67,0.75,1.42,1,1,0.5,0.75,0.75,1,0.42,0.75,0.75,1.25,0.75,1.17,0.5,0.92,0.92,0.75,0.75,1,0,0.5,0.75,0.5,1,0.5,0.5,0.75,0.75,0.5,0.75,0.25,0.75,0.5,0.75,0.5,0.75,0.5,0.75,0.75,0.5,0.25,0.5],"$ saved / hour":[5647.02285714286,9941.472,4297.66285714286,8538.28363636364,472.405714285714,840.182222222222,1345.55333333333,754.146666666667,569.946666666667,690.393333333333,693.313333333333,618.845714285714,895.233333333333,166.421818181818,1318.74181818182,3462.49454545455,6020.46222222222,493.386666666667,825.625,4031.78,53.0266666666667,134.073333333333,459.941818181818,366.04,564.977777777778,736.266666666667,708.493333333333,499.511111111111,200.542222222222,1288.384,692.777142857143,2183.34,259.68,393.788571428571,1042.58666666667,333.955555555556,177.937777777778,1148.448,194.693333333333,69.6290909090909,71.9466666666667,166.88,490.91,0,196.586666666667,322.38,90.35,191.937777777778,39.7882352941176,0,0,0,0,264.364444444444,0,0,0,0,0,0,0,0,0,0,0,0,0,"NA",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},"columns":[{"id":"SKU","name":"SKU","type":"character","headerStyle":{"background":"#E8ECF0","color":"#2D3436","fontWeight":600},"width":95},{"id":"Product","name":"Product","type":"character","headerStyle":{"background":"#E8ECF0","color":"#2D3436","fontWeight":600},"minWidth":180},{"id":"TTM revenue","name":"TTM revenue","type":"numeric","headerStyle":{"background":"#E8ECF0","color":"#2D3436","fontWeight":600},"cell":["$1.51M","$2.71M","$406k","$974k","$878k","$363k","$853k","$1.08M","$1.00M","$736k","$649k","$173k","$257k","$1.33M","$225k","$207k","$739k","$223k","$29k","$388k","$171k","$339k","$151k","$169k","$612k","$1.95M","$2.01M","$252k","$518k","$212k","$25k","$131k","$25k","$17k","$136k","$214k","$241k","$15k","$211k","$83k","$61k","$208k","$20k","$593k","$140k","$18k","$157k","$131k","$12k","$97k","$53k","$496k","$146k","$23k","$23k","$128k","$107k","$101k","$15k","$80k","$1k","$56k","$8k","$6k","$48k","$41k","$3k","$37k","$132k","$25k","$103k","$1k","$90k","$38k","$9k","$8k","$26k","$4k","$24k","$3k","$3k","$3k","$22k","$3k","$19k","$2k","$237","$13k","$4k","$2k"],"align":"right","style":[{"background":"#81BEB6"},{"background":"#1E8C7E"},{"background":"#DDEDEB"},{"background":"#AED5D0"},{"background":"#B7DAD5"},{"background":"#E1F0EE"},{"background":"#B7DAD5"},{"background":"#A4D1CB"},{"background":"#ABD4CF"},{"background":"#C2DFDC"},{"background":"#C9E3E0"},{"background":"#F1F8F7"},{"background":"#EAF4F3"},{"background":"#90C6BF"},{"background":"#EDF5F4"},{"background":"#EDF5F4"},{"background":"#C2DFDC"},{"background":"#EDF5F4"},{"background":"#FCFDFD"},{"background":"#DFEEEC"},{"background":"#F1F8F7"},{"background":"#E1F0EE"},{"background":"#F1F8F7"},{"background":"#F1F8F7"},{"background":"#CBE4E1"},{"background":"#5DACA2"},{"background":"#58A99F"},{"background":"#EAF4F3"},{"background":"#D4E9E6"},{"background":"#EDF5F4"},{"background":"#FCFDFD"},{"background":"#F3F9F8"},{"background":"#FCFDFD"},{"background":"#FCFDFD"},{"background":"#F3F9F8"},{"background":"#EDF5F4"},{"background":"#EAF4F3"},{"background":"#FCFDFD"},{"background":"#EDF5F4"},{"background":"#F8FBFB"},{"background":"#FAFCFC"},{"background":"#EDF5F4"},{"background":"#FCFDFD"},{"background":"#CDE5E2"},{"background":"#F3F9F8"},{"background":"#FCFDFD"},{"background":"#F1F8F7"},{"background":"#F3F9F8"},{"background":"#FFFFFF"},{"background":"#F6FAF9"},{"background":"#FAFCFC"},{"background":"#D6EAE7"},{"background":"#F3F9F8"},{"background":"#FCFDFD"},{"background":"#FCFDFD"},{"background":"#F3F9F8"},{"background":"#F6FAF9"},{"background":"#F6FAF9"},{"background":"#FCFDFD"},{"background":"#F8FBFB"},{"background":"#FFFFFF"},{"background":"#FAFCFC"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FAFCFC"},{"background":"#FAFCFC"},{"background":"#FFFFFF"},{"background":"#FCFDFD"},{"background":"#F3F9F8"},{"background":"#FCFDFD"},{"background":"#F6FAF9"},{"background":"#FFFFFF"},{"background":"#F8FBFB"},{"background":"#FCFDFD"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FCFDFD"},{"background":"#FFFFFF"},{"background":"#FCFDFD"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FCFDFD"},{"background":"#FFFFFF"},{"background":"#FCFDFD"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"}]},{"id":"Quality score","name":"Quality score","type":"numeric","headerStyle":{"background":"#E8ECF0","color":"#2D3436","fontWeight":600},"align":"right","style":[{"background":"#DF908F"},{"background":"#E7ABA9"},{"background":"#DF908F"},{"background":"#E7ABA9"},{"background":"#DF908F"},{"background":"#DF908F"},{"background":"#E7ABA9"},{"background":"#E7ABA9"},{"background":"#E7ABA9"},{"background":"#E7ABA9"},{"background":"#E7ABA9"},{"background":"#DF908F"},{"background":"#E7ABA9"},{"background":"#E7ABA9"},{"background":"#E7ABA9"},{"background":"#E7ABA9"},{"background":"#EFC7C7"},{"background":"#E7ABA9"},{"background":"#D77574"},{"background":"#EFC7C7"},{"background":"#DF908F"},{"background":"#E7ABA9"},{"background":"#E7ABA9"},{"background":"#E7ABA9"},{"background":"#EFC7C7"},{"background":"#F7E4E4"},{"background":"#F7E4E4"},{"background":"#EFC7C7"},{"background":"#EFC7C7"},{"background":"#EFC7C7"},{"background":"#E7ABA9"},{"background":"#EFC7C7"},{"background":"#DF908F"},{"background":"#DF908F"},{"background":"#EFC7C7"},{"background":"#EFC7C7"},{"background":"#EFC7C7"},{"background":"#E7ABA9"},{"background":"#EFC7C7"},{"background":"#E7ABA9"},{"background":"#E7ABA9"},{"background":"#EFC7C7"},{"background":"#E7ABA9"},{"background":"#EFC7C7"},{"background":"#EFC7C7"},{"background":"#E7ABA9"},{"background":"#EFC7C7"},{"background":"#EFC7C7"},{"background":"#DF908F"},{"background":"#E7ABA9"},{"background":"#E7ABA9"},{"background":"#F7E4E4"},{"background":"#EFC7C7"},{"background":"#EFC7C7"},{"background":"#E7ABA9"},{"background":"#EFC7C7"},{"background":"#EFC7C7"},{"background":"#EFC7C7"},{"background":"#E7ABA9"},{"background":"#EFC7C7"},{"background":"#DF908F"},{"background":"#EFC7C7"},{"background":"#E7ABA9"},{"background":"#E7ABA9"},{"background":"#EFC7C7"},{"background":"#EFC7C7"},{"background":"#E7ABA9"},{"background":"#FFFFFF"},{"background":"#F7E4E4"},{"background":"#EFC7C7"},{"background":"#F7E4E4"},{"background":"#E7ABA9"},{"background":"#F7E4E4"},{"background":"#F7E4E4"},{"background":"#EFC7C7"},{"background":"#EFC7C7"},{"background":"#F7E4E4"},{"background":"#EFC7C7"},{"background":"#F7E4E4"},{"background":"#EFC7C7"},{"background":"#EFC7C7"},{"background":"#EFC7C7"},{"background":"#F7E4E4"},{"background":"#EFC7C7"},{"background":"#F7E4E4"},{"background":"#EFC7C7"},{"background":"#EFC7C7"},{"background":"#F7E4E4"},{"background":"#F7E4E4"},{"background":"#F7E4E4"}]},{"id":"Chargebacks 18mo","name":"Chargebacks 18mo","type":"numeric","headerStyle":{"background":"#E8ECF0","color":"#2D3436","fontWeight":600},"cell":["$10k","$12k","$8k","$12k","$827","$2k","$2k","$1k","$855","$1k","$1k","$1k","$1k","$229","$2k","$5k","$7k","$740","$2k","$4k","$119","$201","$632","$549","$636","$552","$531","$562","$226","$805","$1k","$2k","$454","$689","$1k","$376","$200","$1k","$219","$96","$108","$188","$491","$0","$221","$484","$90","$216","$85","$0","$0","$0","$0","$297","$0","$0","$0","$0","$0","$0","$0","$0","$0","$0","$0","$0","$0","$221","$0","$0","$0","$0","$0","$0","$0","$0","$0","$0","$0","$0","$0","$0","$0","$0","$0","$0","$0","$0","$0","$0"],"align":"right","style":[{"background":"#CC4E4B"},{"background":"#C0221F"},{"background":"#D87876"},{"background":"#C32F2C"},{"background":"#FAEFEF"},{"background":"#F5DDDD"},{"background":"#F4DBDB"},{"background":"#F9EBEA"},{"background":"#FAEFEF"},{"background":"#F9EDED"},{"background":"#F9EDED"},{"background":"#F9EBEA"},{"background":"#F8E6E6"},{"background":"#FDFAFA"},{"background":"#F5DDDD"},{"background":"#E7ABA9"},{"background":"#DC8583"},{"background":"#FBF1F1"},{"background":"#F6E2E1"},{"background":"#EAB8B7"},{"background":"#FEFCFC"},{"background":"#FDFAFA"},{"background":"#FBF3F3"},{"background":"#FCF6F6"},{"background":"#FBF3F3"},{"background":"#FCF6F6"},{"background":"#FCF6F6"},{"background":"#FBF3F3"},{"background":"#FDFAFA"},{"background":"#FBF1F1"},{"background":"#F8E8E8"},{"background":"#F3D7D6"},{"background":"#FCF6F6"},{"background":"#FBF1F1"},{"background":"#F9EBEA"},{"background":"#FDF8F8"},{"background":"#FDFAFA"},{"background":"#F7E4E4"},{"background":"#FDFAFA"},{"background":"#FEFCFC"},{"background":"#FEFCFC"},{"background":"#FDFAFA"},{"background":"#FCF6F6"},{"background":"#FFFFFF"},{"background":"#FDFAFA"},{"background":"#FCF6F6"},{"background":"#FEFCFC"},{"background":"#FDFAFA"},{"background":"#FEFCFC"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FDFAFA"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FDFAFA"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"}]},{"id":"Composite priority","name":"Composite priority","type":"numeric","headerStyle":{"background":"#E8ECF0","color":"#2D3436","fontWeight":600},"align":"right","style":[{"background":"#C32D2A","fontWeight":"600"},{"background":"#C53533","fontWeight":"600"},{"background":"#C73C39","fontWeight":"600"},{"background":"#C83E3C","fontWeight":"600"},{"background":"#C8403E","fontWeight":"600"},{"background":"#C8403E","fontWeight":"600"},{"background":"#CA4542","fontWeight":"600"},{"background":"#CA4745","fontWeight":"600"},{"background":"#CB4B49","fontWeight":"600"},{"background":"#CD504E","fontWeight":"600"},{"background":"#CD504E","fontWeight":"600"},{"background":"#CD5250","fontWeight":"600"},{"background":"#CE5452","fontWeight":"600"},{"background":"#CE5452","fontWeight":"600"},{"background":"#CE5452","fontWeight":"600"},{"background":"#CF5754","fontWeight":"600"},{"background":"#D05B59","fontWeight":"600"},{"background":"#D15F5D","fontWeight":"600"},{"background":"#D26462","fontWeight":"600"},{"background":"#D26462","fontWeight":"600"},{"background":"#D46866","fontWeight":"600"},{"background":"#D46866","fontWeight":"600"},{"background":"#D56D6B","fontWeight":"600"},{"background":"#D56D6B","fontWeight":"600"},{"background":"#D56D6B","fontWeight":"600"},{"background":"#D77574","fontWeight":"600"},{"background":"#D87876","fontWeight":"600"},{"background":"#D87876","fontWeight":"600"},{"background":"#D87876","fontWeight":"600"},{"background":"#D87876","fontWeight":"600"},{"background":"#D97A78","fontWeight":"600"},{"background":"#D97C7A","fontWeight":"600"},{"background":"#D97C7A","fontWeight":"600"},{"background":"#DA7E7D","fontWeight":"600"},{"background":"#DA7E7D","fontWeight":"600"},{"background":"#DB817F","fontWeight":"600"},{"background":"#DC8583","fontWeight":"600"},{"background":"#DC8583","fontWeight":"600"},{"background":"#DC8786","fontWeight":"600"},{"background":"#DC8786","fontWeight":"600"},{"background":"#DD8988","fontWeight":"600"},{"background":"#DE8C8A","fontWeight":"600"},{"background":"#DE8E8C","fontWeight":"600"},{"background":"#DF908F","fontWeight":"600"},{"background":"#DF908F","fontWeight":"600"},{"background":"#DF908F","fontWeight":"600"},{"background":"#E09291","fontWeight":"600"},{"background":"#E09493","fontWeight":"600"},{"background":"#E09493","fontWeight":"600"},{"background":"#E19795","fontWeight":"600"},{"background":"#E39D9C","fontWeight":"600"},{"background":"#E5A4A3","fontWeight":"600"},{"background":"#E5A4A3","fontWeight":"600"},{"background":"#E5A6A5","fontWeight":"600"},{"background":"#E6A8A7","fontWeight":"600"},{"background":"#E7ABA9","fontWeight":"600"},{"background":"#E7ABA9","fontWeight":"600"},{"background":"#E7ADAC","fontWeight":"600"},{"background":"#E8AFAE","fontWeight":"600"},{"background":"#E8B1B0","fontWeight":"600"},{"background":"#E8B1B0","fontWeight":"600"},{"background":"#E9B3B2","fontWeight":"600"},{"background":"#E9B3B2","fontWeight":"600"},{"background":"#EAB6B5","fontWeight":"600"},{"background":"#EAB6B5","fontWeight":"600"},{"background":"#EAB6B5","fontWeight":"600"},{"background":"#EAB8B7","fontWeight":"600"},{"background":"#EAB8B7","fontWeight":"600"},{"background":"#EBBAB9","fontWeight":"600"},{"background":"#ECBCBB","fontWeight":"600"},{"background":"#ECBEBE","fontWeight":"600"},{"background":"#ECBEBE","fontWeight":"600"},{"background":"#EDC1C0","fontWeight":"600"},{"background":"#EFC9C9","fontWeight":"600"},{"background":"#EFC9C9","fontWeight":"600"},{"background":"#F0CCCB","fontWeight":"600"},{"background":"#F0CCCB","fontWeight":"600"},{"background":"#F1CECD","fontWeight":"600"},{"background":"#F1D0CF","fontWeight":"600"},{"background":"#F1D0CF","fontWeight":"600"},{"background":"#F2D2D2","fontWeight":"600"},{"background":"#F2D2D2","fontWeight":"600"},{"background":"#F2D2D2","fontWeight":"600"},{"background":"#F3D5D4","fontWeight":"600"},{"background":"#F3D5D4","fontWeight":"600"},{"background":"#F3D7D6","fontWeight":"600"},{"background":"#F4D9D8","fontWeight":"600"},{"background":"#F4D9D8","fontWeight":"600"},{"background":"#F6E0DF","fontWeight":"600"},{"background":"#F8E6E6","fontWeight":"600"}]},{"id":"Est. fix hours","name":"Est. fix hours","type":"numeric","headerStyle":{"background":"#E8ECF0","color":"#2D3436","fontWeight":600},"cell":["1.17","0.83","1.17","0.92","1.17","1.50","1.00","1.00","1.00","1.00","1.00","1.17","1.00","0.92","0.92","0.92","0.75","1.00","1.33","0.67","1.50","1.00","0.92","1.00","0.75","0.50","0.50","0.75","0.75","0.42","1.17","0.67","1.17","1.17","0.75","0.75","0.75","0.83","0.75","0.92","1.00","0.75","0.67","0.75","0.75","1.00","0.67","0.75","1.42","1.00","1.00","0.50","0.75","0.75","1.00","0.42","0.75","0.75","1.25","0.75","1.17","0.50","0.92","0.92","0.75","0.75","1.00","—","0.50","0.75","0.50","1.00","0.50","0.50","0.75","0.75","0.50","0.75","0.25","0.75","0.50","0.75","0.50","0.75","0.50","0.75","0.75","0.50","0.25","0.50"],"align":"right"},{"id":"$ saved / hour","name":"$ saved / hour","type":"numeric","headerStyle":{"background":"#E8ECF0","color":"#2D3436","fontWeight":600},"cell":["$5.6k/hr","$9.9k/hr","$4.3k/hr","$8.5k/hr","$472/hr","$840/hr","$1.3k/hr","$754/hr","$570/hr","$690/hr","$693/hr","$619/hr","$895/hr","$166/hr","$1.3k/hr","$3.5k/hr","$6.0k/hr","$493/hr","$826/hr","$4.0k/hr","$53/hr","$134/hr","$460/hr","$366/hr","$565/hr","$736/hr","$708/hr","$500/hr","$201/hr","$1.3k/hr","$693/hr","$2.2k/hr","$260/hr","$394/hr","$1.0k/hr","$334/hr","$178/hr","$1.1k/hr","$195/hr","$70/hr","$72/hr","$167/hr","$491/hr","$0/hr","$197/hr","$322/hr","$90/hr","$192/hr","$40/hr","$0/hr","$0/hr","$0/hr","$0/hr","$264/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","—","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr","$0/hr"],"align":"right","style":[{"background":"#7EBDB5"},{"background":"#1E8C7E"},{"background":"#9ECDC7"},{"background":"#3D9C90"},{"background":"#F3F9F8"},{"background":"#EDF5F4"},{"background":"#DFEEEC"},{"background":"#EDF5F4"},{"background":"#F1F8F7"},{"background":"#EFF6F5"},{"background":"#EFF6F5"},{"background":"#F1F8F7"},{"background":"#EAF4F3"},{"background":"#FAFCFC"},{"background":"#E1F0EE"},{"background":"#B0D6D1"},{"background":"#75B8B0"},{"background":"#F3F9F8"},{"background":"#EDF5F4"},{"background":"#A2CFCA"},{"background":"#FCFDFD"},{"background":"#FCFDFD"},{"background":"#F3F9F8"},{"background":"#F6FAF9"},{"background":"#F1F8F7"},{"background":"#EFF6F5"},{"background":"#EFF6F5"},{"background":"#F3F9F8"},{"background":"#FAFCFC"},{"background":"#E1F0EE"},{"background":"#EFF6F5"},{"background":"#CDE5E2"},{"background":"#F8FBFB"},{"background":"#F6FAF9"},{"background":"#E8F3F2"},{"background":"#F8FBFB"},{"background":"#FAFCFC"},{"background":"#E4F1EF"},{"background":"#FAFCFC"},{"background":"#FCFDFD"},{"background":"#FCFDFD"},{"background":"#FAFCFC"},{"background":"#F3F9F8"},{"background":"#FFFFFF"},{"background":"#FAFCFC"},{"background":"#F8FBFB"},{"background":"#FCFDFD"},{"background":"#FAFCFC"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#F8FBFB"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"},{"background":"#FFFFFF"}]}],"filterable":true,"searchable":true,"defaultSorted":[{"id":"Composite priority","desc":true}],"defaultPageSize":15,"highlight":true,"striped":true,"theme":{"borderColor":"#d8d8d8","stripedColor":"#fafafa","highlightColor":"#f3eaea","cellPadding":"6px 10px","style":{"fontFamily":"'Helvetica Neue', Inter, system-ui, sans-serif","fontSize":"0.88rem"}},"dataKey":"4c15ee2fc055e95df9299f0fc4c0352f"},"children":[]},"class":"reactR_markup"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="monday-morning" class="level2">
<h2 class="anchored" data-anchor-id="monday-morning">Monday morning</h2>
<p>Here is what Monday morning looks like today at Cinderhaven.</p>
<p>The ops manager opens four retailer portals, downloads four CSV files with four different column headers, pastes them into the Excel workbook she built six months ago, adjusts column mappings because Costco changed their export format after a system update, refreshes the pivot table, and spends fifteen minutes before the meeting reconciling a number that doesn’t match the broker’s Friday email. The discrepancy is a store count definition. She doesn’t have time to find out which one is right. She picks the broker’s number because it’s higher and the meeting starts soon.</p>
<p>The meeting starts. The CEO asks why Cranberry Mostarda dropped 15% at Costco. She doesn’t have a ready answer. The pivot table flagged the drop but doesn’t link to a cause. Was it a stockout? A planogram reset? A data-driven deauthorization at two locations? The information exists in four different systems. None of them talk to each other. She says she’ll look into it. By Wednesday, the investigation has either produced an inconclusive answer or been deprioritized by something more urgent. Next Monday, the same 90 minutes happen again.</p>
<p>This cycle consumes 15 to 20 hours a month. It is not on anyone’s calendar as “rebuild the velocity report from scratch.” It is just what Monday morning costs.</p>
<p>Here is what Monday morning looks like after the product master is clean and the dashboard is live.</p>
<p>The ops manager opens one screen fifteen minutes before the meeting. All four retailers. Velocity by SKU, filterable by retailer, product line, and quality tier. She clicks into Cranberry Mostarda at Costco. The velocity chart shows the 15% drop started three weeks ago. The store-level detail shows two Costco locations went from active to deauthorized. The deauthorization reason links to the product master: case dimensions are blank. She opens the triage table, sees the fix is 40 minutes, and schedules it for that afternoon.</p>
<p>The CEO asks about Cranberry Mostarda. The ops manager already knows the answer. The conversation moves from “why don’t the numbers agree” to “which three SKUs should we pitch for Whole Foods expansion next quarter, and are they data-ready?”</p>
<p>The 90 minutes are not optimized. They are gone. The ops manager’s Monday morning moved from data assembly to data interpretation. The difference is not a better spreadsheet. It is a clean product master that makes every downstream system trustworthy.</p>
</section>
<section id="the-sequence" class="level2">
<h2 class="anchored" data-anchor-id="the-sequence">The sequence</h2>
<p>The work described in this report is four phases of specific, bounded tasks, each one producing a deliverable that makes the next one possible. The total calendar time is approximately two weeks. The total effort is approximately 30 hours of data entry and two to three days of process and tooling work.</p>
<p>Phase one takes an afternoon. Correct the nine invalid GTIN-14 check digits. Each one is a ten-minute fix: open the record, recalculate the check digit, type the correct number. While the corrections propagate through OneWorldSync, move to the brand owner fields. Replace the seventeen “NA” values with “Cinderhaven Provisions.” Submit the initial OneWorldSync registrations for SKUs that are currently listed as “Not Registered.”</p>
<p>When phase one is done, 60% of the chargeback bill stops. The nine GTIN corrections alone eliminate $35,000 a year in penalties. The first clean settlement statement arrives within 30 to 60 days. The retailer readiness pass rate at Walmart moves from 44% to approximately 80%.</p>
<p>Phase two takes a week. Complete every remaining missing field across the catalog. Case dimensions on 21 SKUs, which means pulling physical product and measuring it. Country of origin on 6 SKUs. Remaining OneWorldSync registrations. This is the physical work: a tape measure, a scale, a phone call to a supplier for imported ingredients. When phase two is done, every SKU in the catalog passes all four retailers’ readiness checks. The 50 SKUs currently failing at Walmart become eligible for submission. The $18.2 million in at-risk revenue is secured.</p>
<p>Phase three takes two days. This is the phase that prevents the first two from being wasted. Without a gate between data entry and the live product master, the next SKU launch will introduce the same defects that phases one and two just cleaned. The broker intake checklist is the simplest version of that gate: eight required fields, five minutes to complete, applied to every entry path. The validation logic can be as simple as a check digit calculation that runs when a GTIN is entered and blocks the save if it fails. The technology is trivial. The discipline is the deliverable.</p>
<p>Phase four takes two days. Deploy the Monday Morning Dashboard. Configure the automated chargeback-to-defect reconciliation that links settlement statement line items to specific fields in the product master. Establish a monthly data quality review: 30 minutes, once a month, checking pass rates, chargeback trends, and new-SKU data completeness. When phase four is done, the visibility gap closes. The $691-a-month problem that nobody saw becomes a $0-a-month problem that everybody monitors.</p>
<p>The four phases build on each other. Phase one produces immediate financial return. Phase two eliminates the remaining exposure and unlocks expansion. Phase three prevents recurrence. Phase four makes the system self-monitoring. Skip any phase and the value of the others degrades. Fix the GTINs but don’t install the gate, and the next product launch introduces new defects. Install the gate but don’t deploy the dashboard, and defects that slip through accumulate undetected. The sequence is not arbitrary. It is a dependency chain.</p>
<p>The total: 27 hours of data entry eliminates $56,000 a year in direct chargebacks. Two days of process work prevents recurrence. Two days of tooling work makes the system visible. The cost of dirty data at the current scale is $361,000 a year. At the growth target, it exceeds $600,000. The cost of fixing it is two weeks.</p>
<div class="callout callout-style-simple callout-tip no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><em>The same five inputs that produced the $361,000 figure for Cinderhaven — SKU count, retailer count, annual chargebacks, data quality pass rate, and revenue per SKU — work for any specialty food brand. Plug in your own numbers and see your own annual cost, scale projection, and data-debt density score:</em> <a href="https://lailarallc.shinyapps.io/data-debt-calculator/"><strong>Estimate your own data debt →</strong></a></p>
</div>
</div>
</div>
</section>
</section>
<section id="part-4-the-evidence" class="level1">
<h1>Part 4: The Evidence</h1>
<p><em>These sections appear as collapsible panels in the HTML report and as separate pages in the PDF.</em></p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Revenue-weighted field completeness
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Chart 5 shows nine data defect categories ranked by the share of TTM revenue they affect. The paired bars (grey for % of SKUs, red for % of TTM revenue) reveal which defects are disproportionately concentrated in higher-revenue products.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/charts/05_revenue_weighted_completeness.png" class="img-fluid figure-img" alt="Paired-bar chart of nine defect categories, comparing share of SKUs (grey) to share of TTM revenue (red)."></p>
<figcaption>Revenue-weighted field completeness.</figcaption>
</figure>
</div>
<p>OneWorldSync incompleteness is nearly universal: 90% of SKUs and 90% of revenue. This is a catalog-wide infrastructure problem, not a defect pattern.</p>
<p>The three most revealing rows are Invalid GTIN-14, Missing brand owner, and Missing country. In each case, the red bar extends further right than the grey. Invalid GTIN-14 is the starkest: 10% of SKUs but 25.7% of revenue. The defect is concentrated in the products that matter most. This is consistent with the finding in Part 2: the highest-revenue SKUs have the worst data.</p>
<p>One exception runs the other direction. Implausible case weight affects 46.7% of SKUs but only 31.2% of revenue. This defect concentrates in smaller, lower-revenue products. It is the only defect category where fixing by quality score alone would approximately match fixing by revenue priority.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Retailer readiness: per-retailer breakdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The retailer readiness analysis tests every SKU against each contracted retailer’s published required-field set. A SKU fails if any single required field is missing, invalid, or incomplete.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Retailer</th>
<th style="text-align: right;">Required fields</th>
<th style="text-align: right;">SKUs passing</th>
<th style="text-align: right;">SKUs failing</th>
<th style="text-align: right;">Mean fields short (failing SKUs)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Walmart</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">1.72</td>
</tr>
<tr class="even">
<td>Costco</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">1.68</td>
</tr>
<tr class="odd">
<td>UNFI</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">1.51</td>
</tr>
<tr class="even">
<td>Whole Foods</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">0.33</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/charts/20_retailer_setup_readiness_stacked.png" class="img-fluid figure-img" alt="Stacked bar chart of pass/fail SKU counts per retailer."></p>
<figcaption>Retailer item-setup readiness, pass/fail counts.</figcaption>
</figure>
</div>
<p>The pass rates track directly with how many fields each retailer requires. Walmart demands the most and has the lowest pass rate. Whole Foods requires the least and has the highest. Most failing SKUs are short by one or two fields, not five or six. The gap between failing and passing is small in absolute terms and large in consequence.</p>
<p>The “mean fields short” column matters for planning. Fix brand owner and GTIN across the catalog and Walmart’s pass rate jumps from 44% to approximately 80%. The same two fields move the needle at Costco and UNFI. Whole Foods is already at 70% and its remaining failures are almost all single-field, meaning most are one fix away from passing.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Chargeback trend analysis
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Monthly chargeback dollars have held roughly flat at about $5,000 per month over the 18-month observation window. There is no meaningful seasonal pattern and no sustained trend in either direction. This is consistent with the underlying cause: the defects are static. An invalid check digit does not get worse over time. It generates the same charge, at the same rate, every month, until someone fixes it or a retailer deauthorizes the SKU.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/charts/15_monthly_chargeback_trend.png" class="img-fluid figure-img" alt="Line chart of monthly chargeback dollars showing a roughly flat trend at about $5,000 per month."></p>
<figcaption>Monthly chargeback dollars over the 18-month window.</figcaption>
</figure>
</div>
<p>Chart 16 overlays monthly chargebacks against monthly scan revenue. Revenue is stable at $1.8 to $2.5 million per month. Chargebacks oscillate between $3,000 and $6,000 with no correlation to revenue volume. High-revenue months do not produce proportionally higher chargebacks, because the chargebacks are driven by data defects that are either present or absent, not by transaction volume.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/charts/16_monthly_chargebacks_vs_scan.png" class="img-fluid figure-img" alt="Dual-axis line chart of monthly chargebacks and monthly scan revenue showing no correlation."></p>
<figcaption>Monthly chargebacks overlaid on monthly scan revenue.</figcaption>
</figure>
</div>
<p>This lack of correlation is itself a finding. It means chargebacks will not self-correct with growth. Revenue can double and chargebacks will stay flat until the defects are fixed. It also means chargebacks will not decline with a sales downturn. They are a fixed cost disguised as a variable one.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Growth projection with assumptions and sensitivity
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stage</th>
<th style="text-align: right;">SKUs</th>
<th style="text-align: right;">Retailers</th>
<th style="text-align: right;">Projected annual chargebacks</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Current</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">$59,000</td>
</tr>
<tr class="even">
<td>Stage 2</td>
<td style="text-align: right;">225</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">$220,000</td>
</tr>
<tr class="odd">
<td>Stage 3</td>
<td style="text-align: right;">450</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">$587,000</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/charts/12_growth_projection_chargebacks.png" class="img-fluid figure-img" alt="Bar chart of projected annual chargebacks at current scale, Stage 2, and Stage 3."></p>
<figcaption>Growth projection of annual chargebacks at three SKU/retailer stages.</figcaption>
</figure>
</div>
<p>The projection is linear: it multiplies the current per-SKU chargeback rate by the expanded SKU and retailer counts. This is a floor estimate, not a ceiling. In practice, defect rates tend to degrade during rapid growth because data entry processes that barely work at 90 SKUs break down entirely at 225. New SKUs launch faster, with less review, through more entry paths. The companies that scale from $25 million to $55 million without fixing their product data don’t experience a linear increase in chargebacks. They experience an accelerating one.</p>
<p>The sensitivity: if the defect rate degrades by 25% during growth, Stage 2 chargebacks rise from $220,000 to $275,000 and Stage 3 from $587,000 to $734,000.</p>
<p>The assumption that matters most is not the defect rate. It’s the retailer count. Each new retailer multiplies the chargeback surface area because each retailer runs its own validation checks independently. A SKU with an invalid GTIN generates one charge per retailer per month. At 4 retailers, that’s 4 charges. At 8, it’s 8. Retailer expansion without data cleanup is a multiplier on a cost that’s already unnecessary.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>New vs.&nbsp;old SKU: a null finding
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We tested whether SKU age predicts data quality. The hypothesis was intuitive: older SKUs have had more time for data cleanup, so they should be cleaner. Newer SKUs were entered more recently, possibly more carelessly.</p>
<p>The data shows no relationship. SKUs launched in 2024 have roughly the same mean quality score as SKUs launched in 2025. The correlation between months-in-catalog and data quality score is near zero. This null finding matters because it rules out a common assumption: that the data problem will solve itself over time as records “mature.” It won’t. Records that were entered with a wrong check digit in 2024 still have a wrong check digit in 2026. Age does not fix data. People fix data. Without an active process, the defects persist indefinitely.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Benchmarking context
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Direct benchmarks for specialty food chargeback rates are not publicly available at sufficient granularity to make precise comparisons. The following are directional reference points drawn from industry reports and trade publications:</p>
<p>Retailer chargeback rates across consumer packaged goods typically range from 1% to 5% of gross sales for companies without automated data management. Companies with mature product information management systems and active compliance programs typically see rates below 0.5%.</p>
<p>Cinderhaven’s overall chargeback rate is 0.23% of gross revenue ($59,000 against $25.55 million). This is low by industry standards. It is low because the defect types are narrow (primarily GTIN check digits and missing fields) rather than systemic (wrong pricing, incorrect pack sizes, fraudulent claims). The low rate does not mean the problem is small. It means the problem is concentrated and fixable. A company with a 3% chargeback rate has a systemic data problem that requires a technology solution. Cinderhaven has a clerical problem that requires 27 hours of data entry.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What this report does not cover
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This audit examines product master data quality and its financial impact through chargebacks, stalled launches, retailer readiness, and shelf loss. It does not cover:</p>
<p>Pricing strategy. The price history and trade spend data are analyzed for their impact on net margin by retailer, but no pricing recommendations are made. Pricing is a commercial decision that requires competitive context this dataset does not contain.</p>
<p>Promotional effectiveness. The promotions data is reported as context. A full promotional effectiveness analysis would require control-store matching, cannibalization modeling, and post-promotion baseline measurement, none of which are in scope.</p>
<p>Demand forecasting. Scan data is used to calculate velocity and identify trends. It is not used to project demand. Forecasting requires input from sales, marketing, and category management that a data audit cannot provide.</p>
<p>Supply chain operations. Short shipments and late deliveries account for 4.4% of chargebacks. These are flagged but not analyzed because they are logistics issues, not data issues.</p>
<p>Competitor analysis. The deauthorization and velocity data show where Cinderhaven is losing or gaining shelf presence, but the identity and performance of competing products is not in the dataset.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>How I’d do this differently with real data
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This section is for the portfolio audience: data professionals, hiring managers, and technical evaluators assessing the methodology.</p>
<p>The synthetic dataset was designed to mimic the structure and distribution of real retail product data. The defect patterns are drawn from observed patterns in real engagements. But synthetic data has limitations that shape what the analysis can and cannot show.</p>
<p>With real data, four things would change.</p>
<p>First, the chargeback-to-defect linkage would be richer. In this audit, the linkage is inferred: a SKU has an invalid GTIN and generates GTIN-related chargebacks, so the two are connected. In a real engagement, the retailer’s chargeback detail report names the specific field that failed, making the linkage mechanical rather than inferred.</p>
<p>Second, the stalled-launch model would be tighter. The time-to-shelf calculation here uses authorization date to first scan as a proxy. Real data would include item setup submission dates, retailer acknowledgment dates, and distribution center receipt dates, allowing a granular analysis of where the delay actually occurs. The proxy tells you there is a gap. The real data tells you where to intervene.</p>
<p>Third, the promotional lift analysis would be meaningful. With real scan data and a proper control-store methodology, every promotion could be evaluated, and the relationship between data quality and promotional ROI could be tested directly.</p>
<p>Fourth, the competitive context would exist. Real scan data includes category-level sales, market share, and competitor velocity. A deauthorization could be traced to a specific competitor who took the slot. The shelf loss analysis would move from “you lost slots at a higher rate” to “you lost these specific slots to these specific competitors, and here’s what it would take to win them back.”</p>
<p>The methodology in this report is designed to survive that transition. Every analytical frame works the same way with real data. The numbers change. The structure does not. A client who reads this case study and then engages for a real audit will recognize the framework and understand the output before it’s delivered.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Data model and query library
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The analysis runs against a SQLite database containing nine tables: product_master (90 rows), sku_costs (90), stores (902), distribution_log (12,507), chargebacks (381), promotions (198), price_history (398), scan_data (1,118,009), and retailer_requirements (29).</p>
<p>The companion SQL query library (53 queries, available in the product-data-audit-queries repository) covers every analytical frame used in this report. Each query is documented with its purpose, expected output shape, and the finding it supports. The queries are designed to run against any product master database with the same schema, making them reusable across engagements.</p>
<p>The R pipeline (14 analytical frames, 21 charts, and 4 output artifacts) regenerates from a single command: <code>Rscript R/run_all.R</code>. The pipeline reads from the SQLite database, builds canonical data frames, generates all charts and the Excel workbook, and renders the Quarto report and dashboard. Total execution time: under two minutes.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note on dataset construction
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The Cinderhaven dataset is synthetic. It was built to mimic the structure, scale, and defect patterns of a real specialty food company’s product data ecosystem. The data generation log (data_generation_log.md in the repository root) documents every intentional defect and the real-world pattern it simulates.</p>
<p>Key design decisions in the synthetic data:</p>
<p>GTIN check digits were misaligned on 10% of SKUs (9 of 90) to mirror observed human data-entry error rates. The audit’s validation logic matches the dataset’s own algorithm. A strict GS1 implementation would flag additional SKUs.</p>
<p>Chargeback concentrations follow a Pareto distribution seeded from observed patterns in real engagements: a small number of SKUs generate a disproportionate share of chargeback dollars. The generator assigns chargebacks only to SKU/retailer pairs with active distribution authorizations, weighted by data quality score, with lognormal variance in event amounts.</p>
<p>OneWorldSync registration statuses were distributed to produce a 10% complete rate (9 of 90 SKUs), reflecting the typical state of a mid-market specialty food company that has started the registration process but not prioritized it.</p>
<p>Serving size strings were intentionally varied across 14 formats to simulate the real-world problem of inconsistent data entry across multiple entry sources.</p>
<p>Time-to-shelf was modeled with a quality-dependent lag: SKUs with lower data quality scores receive longer delays between store authorization and first scan, calibrated to produce a roughly 3x spread between the worst and best quality tiers.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Methodology notes
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>All dollar estimates in this report state their assumptions at point of claim. The key methodological choices:</p>
<p>Chargeback annualization: 18-month totals are multiplied by 12/18 to produce annual run rates. This assumes the monthly chargeback rate is stationary. Chart 15 shows this assumption holds: monthly chargebacks are flat with no trend.</p>
<p>Stalled-launch cost estimate ($234,000): calculated as the revenue difference between actual time-to-shelf and best-tier time-to-shelf, summed across all SKUs outside the best tier. Assumes that revenue accrues linearly with shelf time and that delayed revenue is not recovered in later periods. Both assumptions are conservative: in practice, launch windows are time-sensitive and lost early velocity is difficult to recapture.</p>
<p>Shelf loss cost estimate ($68,000): calculated from the differential deauthorization rate between bottom-half and top-half quality SKUs, applied to the average revenue per deauthorized SKU. Assumes the quality-correlated deauthorization differential is entirely attributable to data quality. In reality, some portion of the differential may reflect other factors (poor velocity, category resets, shelf space optimization). The estimate should be treated as an upper bound on the data-quality contribution.</p>
<p>Total cost model ($361,000): sum of chargebacks ($59,000), stalled launches ($234,000), and shelf loss ($68,000). Trade spend erosion is identified as a fourth cost category but not quantified because isolating the data-quality share of trade spend requires assumptions this audit does not make.</p>
<p>Data quality scoring: each SKU is scored on 8 binary checks (GTIN-14 valid, UPC-12 valid, brand owner present, country of origin present, case weight plausible, case dimensions present, OneWorldSync complete, serving size standardized). Score = (checks passed / 8) x 100. The scoring is deliberately simple and transparent: every dimension is equally weighted, and the reader can see exactly which checks each SKU passes or fails.</p>
<p>Fix-priority composite: revenue rank (40%), quality rank (30%), chargeback rank (30%). Ranks are percentile-based (1 = best/highest). Effort is shown separately, not incorporated into the composite. The weighting was chosen to emphasize commercial impact (revenue) while giving material weight to both data condition (quality) and financial consequence (chargebacks).</p>
</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>