ROOT <- "C:/Users/mssha/OneDrive/Desktop/product-data-health-audit"
sku_dim <- readRDS(file.path(ROOT, "output/frames/sku_dim.rds"))
sku_master_full <- readRDS(file.path(ROOT, "output/frames/sku_master_full.rds"))
ce <- readRDS(file.path(ROOT, "output/frames/chargebacks_enriched.rds"))

cat("== sku_dim columns ==\n")
print(names(sku_dim))
cat("\n== sku_master_full columns ==\n")
print(names(sku_master_full))
cat("\n== chargebacks_enriched columns ==\n")
print(names(ce))
cat("\n== distinct reasons ==\n")
print(unique(ce$reason))
cat("\n== month_date range ==\n")
print(range(ce$month_date))
